/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#f6faff",
        foreground: "#001e2e",
        "surface-container-low": "#ebf5ff",
        "on-tertiary-container": "#353c43",
        "on-primary-container": "#00443b",
        "on-tertiary-fixed-variant": "#40484e",
        "surface-container-highest": "#c8e6ff",
        "surface-container-high": "#d4ebff",
        "primary-fixed-dim": "#64dac5",
        "on-background": "#001e2e",
        "surface-container": "#dff0ff",
        "primary": {
          DEFAULT: "#006b5e",
          foreground: "#ffffff",
          50: '#ecfdf5',
          100: '#d1fae5',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
        },
        "tertiary-fixed": "#dce3eb",
        "primary-fixed": "#82f6e1",
        "inverse-surface": "#133346",
        "inverse-primary": "#64dac5",
        "outline": "#6d7a76",
        "surface-bright": "#f6faff",
        "secondary": {
          DEFAULT: "#466178",
          foreground: "#ffffff",
        },
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#c0c7cf",
        "on-error-container": "#93000a",
        "tertiary-container": "#a0a7ae",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "primary-container": "#3db8a5",
        "on-primary-fixed-variant": "#005046",
        "on-surface-variant": "#3d4946",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#cce5ff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#00201b",
        "secondary-container": "#c7e3fe",
        "inverse-on-surface": "#e5f2ff",
        "surface-variant": "#c8e6ff",
        "tertiary": "#585f66",
        "secondary-fixed-dim": "#aecae5",
        "outline-variant": "#bcc9c5",
        "surface": "#f6faff",
        "on-secondary-fixed-variant": "#2e4960",
        "on-secondary-fixed": "#001e31",
        "error": "#ba1a1a",
        "surface-tint": "#006b5e",
        "on-tertiary-fixed": "#151c22",
        "on-surface": "#001e2e",
        "surface-dim": "#bfdef7",
        "on-secondary-container": "#4b657d",
        "error-container": "#ffdad6",
        "amber-15": "rgba(245, 158, 11, 0.15)",
        "amber-600": "#d97706",
        "deep-navy": "#0d2b40",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        bhunetra: {
          emerald: '#059669',
          darkEmerald: '#064e3b',
          gold: '#d97706',
          slate: '#0f172a',
          navy: '#020617',
          surface: '#1e293b',
        }
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.25rem",
        "20px": "20px",
        full: "9999px"
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        "card-padding": "24px",
        "container-margin": "32px",
        "sidebar-width": "280px"
      },
      fontFamily: {
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "hindi-text": ["Noto Sans Devanagari", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "mono-code": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "500" }],
        "hindi-text": ["18px", { "lineHeight": "30px", "fontWeight": "400" }],
        "label-sm": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "mono-code": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      },
      keyframes: {
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.6" },
        },
        "scan-line": {
          "0%": { top: "0%" },
          "100%": { top: "100%" },
        }
      },
      animation: {
        "pulse-subtle": "pulse-subtle 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "scan": "scan-line 2.5s ease-in-out infinite alternate",
      },
    },
  },
  plugins: [],
}
