"""
Seed Data Script for BHUNETRA
Pre-populates Firestore / Mock DB with all 30 demo land & property records
covering all 10 document categories (20 Authorized + 10 Tampered/Fraud Demos).
"""
import sys
import logging
from datetime import datetime, timezone

from app.firebase_config import get_db
from app.schemas.common import VerificationStatus

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("bhunetra.seed")

DEMO_RECORDS = [
    # Category 1: 7/12 Extract
    {
        "recordId": "REC-712-PUN-001",
        "docCategory": "712_extract",
        "docId": "DOC-712-2026-001",
        "khasraNumber": "142/3A",
        "khataNumber": "582",
        "ownerName": "रमेश विठ्ठल पाटील (Ramesh Vitthal Patil)",
        "village": "वाघोली",
        "tehsil": "हवेली",
        "district": "पुणे",
        "landArea": "1.45 हेक्टर",
        "ownershipType": "भोगवटादार वर्ग - १",
        "overallConfidence": 0.994,
        "verificationStatus": VerificationStatus.AUTO_APPROVED.value,
        "flaggedFields": [],
        "isForged": False,
        "verifiedBy": "AUTO_ML_ENGINE",
        "verifiedAt": datetime.now(timezone.utc).isoformat(),
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    {
        "recordId": "REC-712-PUN-002",
        "docCategory": "712_extract",
        "docId": "DOC-712-2026-002",
        "khasraNumber": "89/2B",
        "khataNumber": "314",
        "ownerName": "सुरेश गणपत देशमुख (Suresh Ganpat Deshmukh)",
        "village": "माळेगाव बु.",
        "tehsil": "बारामती",
        "district": "पुणे",
        "landArea": "2.80 हेक्टर",
        "ownershipType": "भोगवटादार वर्ग - १",
        "overallConfidence": 0.989,
        "verificationStatus": VerificationStatus.AUTO_APPROVED.value,
        "flaggedFields": [],
        "isForged": False,
        "verifiedBy": "AUTO_ML_ENGINE",
        "verifiedAt": datetime.now(timezone.utc).isoformat(),
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    {
        "recordId": "REC-712-FRAUD-999",
        "docCategory": "712_extract",
        "docId": "DOC-712-2026-999",
        "khasraNumber": "999/X",
        "khataNumber": "9999",
        "ownerName": "विक्रम बनावटराव शिंदे (Unauthorized Fake Claim)",
        "village": "खोट्यावाडी",
        "tehsil": "हवेली",
        "district": "पुणे",
        "landArea": "9.99 हेक्टर",
        "ownershipType": "अनधिकृत फेरफार",
        "overallConfidence": 0.124,
        "verificationStatus": "FLAGGED_FRAUD",
        "flaggedFields": ["khasraNumber", "khataNumber", "stamp", "ownerName"],
        "isForged": True,
        "verifiedBy": None,
        "verifiedAt": None,
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    # Category 2: 8-A Khata Sheet
    {
        "recordId": "REC-8A-NSK-001",
        "docCategory": "8a_khata",
        "docId": "DOC-8A-2026-001",
        "khasraNumber": "105/B",
        "khataNumber": "341",
        "ownerName": "गणेश पांडुरंग पवार (Ganesh Pandurang Pawar)",
        "village": "त्र्यंबकेश्वर",
        "tehsil": "त्र्यंबकेश्वर",
        "district": "नाशिक",
        "landArea": "0.85 हेक्टर",
        "ownershipType": "भोगवटादार वर्ग - १",
        "overallConfidence": 0.991,
        "verificationStatus": VerificationStatus.AUTO_APPROVED.value,
        "flaggedFields": [],
        "isForged": False,
        "verifiedBy": "AUTO_ML_ENGINE",
        "verifiedAt": datetime.now(timezone.utc).isoformat(),
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    {
        "recordId": "REC-8A-NSK-002",
        "docCategory": "8a_khata",
        "docId": "DOC-8A-2026-002",
        "khasraNumber": "74/1",
        "khataNumber": "198",
        "ownerName": "सुनिता अशोक गायकवाड (Sunita Ashok Gaikwad)",
        "village": "जानोरी",
        "tehsil": "दिंडोरी",
        "district": "नाशिक",
        "landArea": "1.60 हेक्टर",
        "ownershipType": "भोगवटादार वर्ग - १",
        "overallConfidence": 0.987,
        "verificationStatus": VerificationStatus.AUTO_APPROVED.value,
        "flaggedFields": [],
        "isForged": False,
        "verifiedBy": "AUTO_ML_ENGINE",
        "verifiedAt": datetime.now(timezone.utc).isoformat(),
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    {
        "recordId": "REC-8A-FRAUD-999",
        "docCategory": "8a_khata",
        "docId": "DOC-8A-2026-999",
        "khasraNumber": "888/Z",
        "khataNumber": "9999",
        "ownerName": "अविनाश बोगसराव कांबळे (Tax Evasion Fake Khata)",
        "village": "नियमबाह्य गाव",
        "tehsil": "निफाड",
        "district": "नाशिक",
        "landArea": "12.50 हेक्टर",
        "ownershipType": "भोगवटादार संशयास्पद",
        "overallConfidence": 0.142,
        "verificationStatus": "FLAGGED_FRAUD",
        "flaggedFields": ["khataNumber", "assessment", "stamp"],
        "isForged": True,
        "verifiedBy": None,
        "verifiedAt": None,
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    # Category 3: Urban Property Card (CTS)
    {
        "recordId": "REC-CTS-PUN-001",
        "docCategory": "property_card",
        "docId": "DOC-CTS-2026-001",
        "khasraNumber": "CTS 1204/5",
        "khataNumber": "Sheet 12",
        "ownerName": "प्रकाश नारायण कुलकर्णी (Prakash Narayan Kulkarni)",
        "village": "शिवाजी नगर",
        "tehsil": "हवेली",
        "district": "पुणे",
        "landArea": "350 चौ.मी.",
        "ownershipType": "धारणाधिकार - फ्रीहोल्ड",
        "overallConfidence": 0.995,
        "verificationStatus": VerificationStatus.AUTO_APPROVED.value,
        "flaggedFields": [],
        "isForged": False,
        "verifiedBy": "AUTO_ML_ENGINE",
        "verifiedAt": datetime.now(timezone.utc).isoformat(),
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    {
        "recordId": "REC-CTS-PUN-002",
        "docCategory": "property_card",
        "docId": "DOC-CTS-2026-002",
        "khasraNumber": "CTS 882/A",
        "khataNumber": "Sheet 8",
        "ownerName": "अंजली रवींद्र जोशी (Anjali Ravindra Joshi)",
        "village": "कोथरूड",
        "tehsil": "हवेली",
        "district": "पुणे",
        "landArea": "210 चौ.मी.",
        "ownershipType": "धारणाधिकार - लीजहोल्ड",
        "overallConfidence": 0.990,
        "verificationStatus": VerificationStatus.AUTO_APPROVED.value,
        "flaggedFields": [],
        "isForged": False,
        "verifiedBy": "AUTO_ML_ENGINE",
        "verifiedAt": datetime.now(timezone.utc).isoformat(),
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    {
        "recordId": "REC-CTS-FRAUD-999",
        "docCategory": "property_card",
        "docId": "DOC-CTS-2026-999",
        "khasraNumber": "CTS 9999/ENC",
        "khataNumber": "Sheet 99",
        "ownerName": "अजय बेकायदेशीर कांबळे (Illegal Encroachment Claim)",
        "village": "पुणे शहर",
        "tehsil": "हवेली",
        "district": "पुणे",
        "landArea": "950 चौ.मी.",
        "ownershipType": "बेकायदेशीर ताबा",
        "overallConfidence": 0.151,
        "verificationStatus": "FLAGGED_FRAUD",
        "flaggedFields": ["ctsNumber", "area", "stamp"],
        "isForged": True,
        "verifiedBy": None,
        "verifiedAt": None,
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    # Category 4: Mutation Register (Form 6 Ferfar)
    {
        "recordId": "REC-FER-SAT-001",
        "docCategory": "mutation_register",
        "docId": "DOC-FER-2026-001",
        "khasraNumber": "गट २१५",
        "khataNumber": "फेरफार २८४१",
        "ownerName": "दिलीप शंकर शिंदे (Dilip Shankar Shinde)",
        "village": "ओगलेवाडी",
        "tehsil": "कराड",
        "district": "सातारा",
        "landArea": "1.20 हेक्टर",
        "ownershipType": "भोगवटादार वर्ग - १",
        "overallConfidence": 0.992,
        "verificationStatus": VerificationStatus.AUTO_APPROVED.value,
        "flaggedFields": [],
        "isForged": False,
        "verifiedBy": "AUTO_ML_ENGINE",
        "verifiedAt": datetime.now(timezone.utc).isoformat(),
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    {
        "recordId": "REC-FER-SAT-002",
        "docCategory": "mutation_register",
        "docId": "DOC-FER-2026-002",
        "khasraNumber": "गट १४२/१",
        "khataNumber": "फेरफार १९३२",
        "ownerName": "मोहन यशवंत जाधव (Mohan Yashwant Jadhav)",
        "village": "भुईंज",
        "tehsil": "वाई",
        "district": "सातारा",
        "landArea": "0.95 हेक्टर",
        "ownershipType": "भोगवटादार वर्ग - १",
        "overallConfidence": 0.988,
        "verificationStatus": VerificationStatus.AUTO_APPROVED.value,
        "flaggedFields": [],
        "isForged": False,
        "verifiedBy": "AUTO_ML_ENGINE",
        "verifiedAt": datetime.now(timezone.utc).isoformat(),
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    {
        "recordId": "REC-FER-FRAUD-999",
        "docCategory": "mutation_register",
        "docId": "DOC-FER-2026-999",
        "khasraNumber": "गट ९९९",
        "khataNumber": "फेरफार ९९९९",
        "ownerName": "किरण बेकायदेशीर पाटील (Forged Appeal Claim)",
        "village": "खोटेवाडी",
        "tehsil": "कराड",
        "district": "सातारा",
        "landArea": "5.50 हेक्टर",
        "ownershipType": "संशयास्पद फेरफार",
        "overallConfidence": 0.118,
        "verificationStatus": "FLAGGED_FRAUD",
        "flaggedFields": ["mutationNumber", "stamp", "transactionType"],
        "isForged": True,
        "verifiedBy": None,
        "verifiedAt": None,
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    # Category 5: Registered Sale Deed
    {
        "recordId": "REC-DEED-PUN-001",
        "docCategory": "sale_deed",
        "docId": "DOC-DEED-2026-001",
        "khasraNumber": "गट ३१०/२",
        "khataNumber": "दस्त ४५८२/२०२३",
        "ownerName": "विक्रम बाळासाहेब भोसले (Vikram Balasaheb Bhosale)",
        "village": "उरुळी कांचन",
        "tehsil": "हवेली",
        "district": "पुणे",
        "landArea": "1.10 हेक्टर",
        "ownershipType": "खरेदीदार (Clear Title)",
        "overallConfidence": 0.996,
        "verificationStatus": VerificationStatus.AUTO_APPROVED.value,
        "flaggedFields": [],
        "isForged": False,
        "verifiedBy": "AUTO_ML_ENGINE",
        "verifiedAt": datetime.now(timezone.utc).isoformat(),
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    {
        "recordId": "REC-DEED-PUN-002",
        "docCategory": "sale_deed",
        "docId": "DOC-DEED-2026-002",
        "khasraNumber": "गट १६५/४",
        "khataNumber": "दस्त २९४०/२०२३",
        "ownerName": "संदीप एकनाथ थोरात (Sandeep Eknath Thorat)",
        "village": "पौड",
        "tehsil": "मुळशी",
        "district": "पुणे",
        "landArea": "0.75 हेक्टर",
        "ownershipType": "खरेदीदार (Clear Title)",
        "overallConfidence": 0.991,
        "verificationStatus": VerificationStatus.AUTO_APPROVED.value,
        "flaggedFields": [],
        "isForged": False,
        "verifiedBy": "AUTO_ML_ENGINE",
        "verifiedAt": datetime.now(timezone.utc).isoformat(),
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
    {
        "recordId": "REC-DEED-FRAUD-999",
        "docCategory": "sale_deed",
        "docId": "DOC-DEED-2026-999",
        "khasraNumber": "गट ९९९/वाद",
        "khataNumber": "दस्त ९९९९/२०२३",
        "ownerName": "प्रमोद वादग्रस्त जगताप (Double Selling Fraud)",
        "village": "हडपसर",
        "tehsil": "हवेली",
        "district": "पुणे",
        "landArea": "3.20 हेक्टर",
        "ownershipType": "न्यायालयीन मनाई दस्त",
        "overallConfidence": 0.135,
        "verificationStatus": "FLAGGED_FRAUD",
        "flaggedFields": ["registrationNumber", "stamp", "marketValue"],
        "isForged": True,
        "verifiedBy": None,
        "verifiedAt": None,
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    },
]

def seed_records():
    db = get_db()
    logger.info("🌱 Seeding 30 demo land records into database...")
    for rec in DEMO_RECORDS:
        db.collection("records").document(rec["recordId"]).set(rec)
        if rec["verificationStatus"] == VerificationStatus.PENDING_REVIEW.value:
            queue_data = {
                "queueId": f"Q-{rec['recordId']}",
                "recordId": rec["recordId"],
                "assignedTo": None,
                "priority": "high",
                "status": "pending",
                "flaggedFields": rec["flaggedFields"],
                "overallConfidence": rec["overallConfidence"],
                "createdAt": rec["createdAt"],
            }
            db.collection("verificationQueue").document(f"Q-{rec['recordId']}").set(queue_data)
        logger.info(f"  └─ Seeded record: {rec['recordId']} ({rec['verificationStatus']})")
    logger.info("✅ Database seeded successfully with all 10 document categories.")

if __name__ == "__main__":
    seed_records()
