/*
Official 22 Languages of India (8th Schedule of the Constitution) + English
*/

export const CONSTITUTION_22_LANGUAGES = [
  { code: 'mr', nameEn: 'Marathi', nameNative: 'मराठी', icon: '🚩', script: 'Devanagari' },
  { code: 'hi', nameEn: 'Hindi', nameNative: 'हिन्दी', icon: '🇮🇳', script: 'Devanagari' },
  { code: 'en', nameEn: 'English', nameNative: 'English', icon: '🇬🇧', script: 'Latin' },
  { code: 'bn', nameEn: 'Bengali', nameNative: 'বাংলা', icon: '🇧🇩', script: 'Bengali' },
  { code: 'gu', nameEn: 'Gujarati', nameNative: 'ગુજરાતી', icon: '🏛️', script: 'Gujarati' },
  { code: 'ta', nameEn: 'Tamil', nameNative: 'தமிழ்', icon: '🏛️', script: 'Tamil' },
  { code: 'te', nameEn: 'Telugu', nameNative: 'తెలుగు', icon: '🏛️', script: 'Telugu' },
  { code: 'kn', nameEn: 'Kannada', nameNative: 'ಕನ್ನಡ', icon: '🏛️', script: 'Kannada' },
  { code: 'ml', nameEn: 'Malayalam', nameNative: 'മലയാളം', icon: '🏛️', script: 'Malayalam' },
  { code: 'pa', nameEn: 'Punjabi', nameNative: 'ਪੰਜਾਬੀ', icon: '🏛️', script: 'Gurmukhi' },
  { code: 'or', nameEn: 'Odia', nameNative: 'ଓଡ଼ିଆ', icon: '🏛️', script: 'Odia' },
  { code: 'as', nameEn: 'Assamese', nameNative: 'অসমীয়া', icon: '🏛️', script: 'Bengali-Assamese' },
  { code: 'ur', nameEn: 'Urdu', nameNative: 'اردو', icon: '🏛️', script: 'Perso-Arabic' },
  { code: 'sa', nameEn: 'Sanskrit', nameNative: 'संस्कृतम्', icon: '🕉️', script: 'Devanagari' },
  { code: 'ks', nameEn: 'Kashmiri', nameNative: 'कॉशुर', icon: '🏔️', script: 'Perso-Arabic/Devanagari' },
  { code: 'sd', nameEn: 'Sindhi', nameNative: 'सिन्धी', icon: '🏛️', script: 'Perso-Arabic/Devanagari' },
  { code: 'ne', nameEn: 'Nepali', nameNative: 'नेपाली', icon: '🏔️', script: 'Devanagari' },
  { code: 'kok', nameEn: 'Konkani', nameNative: 'कोंकणी', icon: '🏖️', script: 'Devanagari' },
  { code: 'doi', nameEn: 'Dogri', nameNative: 'डोगरी', icon: '🏛️', script: 'Devanagari' },
  { code: 'mni', nameEn: 'Manipuri (Meitei)', nameNative: 'मइतैलोन', icon: '🏛️', script: 'Meitei/Bengali' },
  { code: 'sat', nameEn: 'Santali', nameNative: 'संताली', icon: '🏛️', script: 'Ol Chiki' },
  { code: 'brx', nameEn: 'Bodo', nameNative: 'बर\'', icon: '🏛️', script: 'Devanagari' },
  { code: 'mai', nameEn: 'Maithili', nameNative: 'मैथिली', icon: '🏛️', script: 'Devanagari' },
]

export function getLanguageByCode(code) {
  return CONSTITUTION_22_LANGUAGES.find((l) => l.code === code) || CONSTITUTION_22_LANGUAGES[0]
}

export const UI_TRANSLATIONS = {
  mr: {
    headerGovIndia: "🇮🇳 भारत सरकार | Govt. of India",
    headerDept: "महाराष्ट्र शासन - महसूल व वन विभाग",
    headerTitle: "भूनेत्रा - राज्य भूमी अभिलेख संगणकीकरण प्रणाली",
    roleTag: "पद (Role):",
    roleOfficer: "तहसीलदार",
    roleVerifier: "तलाठी",
    roleAdmin: "प्रशासक",
    welcome: "पुन्हा स्वागत आहे",
    subtitle: "कृत्रिम बुद्धिमत्ता आधारित भूमी अभिलेख संगणकीकरण प्रणाली",
    totalDigitized: "एकूण डिजिटाईज्ड अभिलेख",
    avgConfidence: "सरासरी अचूकता दर",
    autoApproved: "स्वायत्त स्वीकृत अभिलेख",
    pendingQueue: "महसूल पडताळणी प्रलंबित",
    districtModernization: "जिल्हास्तरीय संगणकीकरण प्रगती",
    today: "आज जोडले",
    highConfidence: "उच्च अचूकता दर",
    awaitingVerifier: "तलाठी/तहसीलदार पडताळणी प्रलंबित",
    ingestBtn: "नवीन ७/१२ अपलोड करा",
    recordsProcessing: "अभिलेख प्रक्रियेत",
    complete: "पूर्ण",
    dashboardTab: "मुख्य पृष्ठ",
    uploadTab: "७/१२ अपलोड",
    queueTab: "महसूल पडताळणी",
    gisTab: "नकाशा / GIS",
  },
  hi: {
    headerGovIndia: "🇮🇳 भारत सरकार | Govt. of India",
    headerDept: "महाराष्ट्र सरकार - राजस्व एवं वन विभाग",
    headerTitle: "भूनेत्र - राज्य भूमि अभिलेख डिजिटलीकरण प्रणाली",
    roleTag: "पद (Role):",
    roleOfficer: "तहसीलदार",
    roleVerifier: "पटवारी / तलाठी",
    roleAdmin: "प्रशासक",
    welcome: "पुनः स्वागत है",
    subtitle: "कृत्रिम बुद्धिमत्ता आधारित भूमि अभिलेख डिजिटलीकरण एवं निगरानी पोर्टल",
    totalDigitized: "कुल डिजिटाइज़्ड अभिलेख",
    avgConfidence: "औसत सटीकता दर",
    autoApproved: "स्वायत्त स्वीकृत रिकॉर्ड्स",
    pendingQueue: "समीक्षा हेतु लंबित",
    districtModernization: "जिला स्तरीय आधुनिकीकरण प्रगति",
    today: "आज जोड़े गए",
    highConfidence: "उच्च सटीकता",
    awaitingVerifier: "राजस्व अधिकारी सत्यापन हेतु लंबित",
    ingestBtn: "नया ७/१२ अपलोड करें",
    recordsProcessing: "रिकॉर्ड्स प्रसंस्करण में",
    complete: "पूर्ण",
    dashboardTab: "मुख्य पृष्ठ",
    uploadTab: "७/१२ अपलोड",
    queueTab: "राजस्व सत्यापन",
    gisTab: "मानचित्र / GIS",
  },
  en: {
    headerGovIndia: "🇮🇳 Govt. of India",
    headerDept: "Govt. of Maharashtra - Revenue & Forest Dept.",
    headerTitle: "BHUNETRA - State Land Records Modernization System",
    roleTag: "Role:",
    roleOfficer: "Revenue Officer",
    roleVerifier: "Field Verifier",
    roleAdmin: "Administrator",
    welcome: "Welcome back",
    subtitle: "AI-assisted land record digitization and monitoring portal",
    totalDigitized: "TOTAL RECORDS DIGITIZED",
    avgConfidence: "AVERAGE CONFIDENCE",
    autoApproved: "AUTO-APPROVED RECORDS",
    pendingQueue: "VERIFICATION BACKLOG",
    districtModernization: "District-Level Modernization Progress",
    today: "today",
    highConfidence: "HIGH CONFIDENCE",
    awaitingVerifier: "Awaiting Human Verifier",
    ingestBtn: "Ingest New Document",
    recordsProcessing: "Records Processing",
    complete: "Complete",
    dashboardTab: "Dashboard",
    uploadTab: "Upload",
    queueTab: "Queue",
    gisTab: "GIS",
  },
  bn: {
    welcome: "স্বাগতম",
    subtitle: "কৃত্রিম বুদ্ধিমত্তা ভিত্তিক ভূমি রেকর্ড ডিজিটাইজেশন পোর্টাল",
    totalDigitized: "মোট ডিজিটাইজড রেকর্ড",
    avgConfidence: "গড় নির্ভুলতার হার",
    autoApproved: "স্বয়ংক্রিয় অনুমোদিত রেকর্ড",
    pendingQueue: "যাচাইয়ের জন্য বিচারাধীন",
    districtModernization: "জেলা স্তরের আধুনিকীকরণের অগ্রগতি",
    today: "আজ যোগ করা হয়েছে",
    highConfidence: "উচ্চ নির্ভুলতা",
    awaitingVerifier: "রাজস্ব কর্মকর্তার অনুমোদনের অপেক্ষায়",
    ingestBtn: "নতুন দলিল আপলোড করুন",
    recordsProcessing: "রেকর্ড প্রক্রিয়াধীন",
    complete: "সম্পূর্ণ",
    dashboardTab: "ড্যাশবোর্ড",
    uploadTab: "আপলোড",
    queueTab: "যাচাইকরণ সারিক",
    gisTab: "মানচিত্র / GIS",
  },
  gu: {
    welcome: "સુવાગતમ",
    subtitle: "એઆઈ આધારિત જમીન રેકોર્ડ ડિજિટાઇઝેશન પોર્ટલ",
    totalDigitized: "કુલ ડિજિટાઇઝ્ડ રેકોર્ડ્સ",
    avgConfidence: "સરેરાશ ચોકસાઈ દર",
    autoApproved: "સ્વચાલિત મંજૂર રેકોર્ડ્સ",
    pendingQueue: "ચકાસણી માટે પેન્ડિંગ",
    districtModernization: "જિલ્લા કક્ષાની આધુનિકીકરણ પ્રગતિ",
    today: "આજે ઉમેરેલ",
    highConfidence: "ઉચ્ચ ચોકસાઈ",
    awaitingVerifier: "મહેસૂલ અધિકારીની રાહ જોવાય છે",
    ingestBtn: "નવો દસ્તાવેજ અપલોડ કરો",
    recordsProcessing: "રેકોર્ડ્સ પ્રક્રિયા હેઠળ",
    complete: "પૂર્ણ",
    dashboardTab: "ડેશબોર્ડ",
    uploadTab: "અપલોડ",
    queueTab: "તપાસણી લાઇન",
    gisTab: "નકશો / GIS",
  },
  ta: {
    welcome: "நல்வரவு",
    subtitle: "செயற்கை நுண்ணறிவு நில ஆவணங்கள் டிஜிட்டல் போர்ட்டல்",
    totalDigitized: "மொத்த டிஜிட்டல் ஆவணங்கள்",
    avgConfidence: "சராசரி துல்லிய விகிதம்",
    autoApproved: "தானியங்கி அங்கீகரிக்கப்பட்ட ஆவணங்கள்",
    pendingQueue: "சரிபார்ப்பிற்கு நிலுவையில் உள்ளது",
    districtModernization: "மாவட்ட வாரியான முன்னேற்றம்",
    today: "இன்று",
    highConfidence: "உயர் துல்லியம்",
    awaitingVerifier: "வருவாய் அலுவலர் ஒப்புதலுக்கு காத்திருக்கிறது",
    ingestBtn: "புதிய ஆவணத்தை பதிவேற்றவும்",
    recordsProcessing: "செயலாக்கத்தில் உள்ளது",
    complete: "நிறைவுற்றது",
    dashboardTab: "முகப்பு",
    uploadTab: "பதிவேற்றம்",
    queueTab: "சரிபார்ப்பு வரிசை",
    gisTab: "வரைபடம் / GIS",
  },
  te: {
    welcome: "సుస్వాగతం",
    subtitle: "ఏఐ ఆధారిత భూ రికార్డుల డిజిటలైజేషన్ పోర్టల్",
    totalDigitized: "మొత్తం డిజిటలైజ్ చేసిన రికార్డులు",
    avgConfidence: "సగటు ఖచ్చితత్వం రేటు",
    autoApproved: "ఆటో-ఆమోదించబడిన రికార్డులు",
    pendingQueue: "పరిశీలన కోసం పెండింగ్‌లో ఉంది",
    districtModernization: "జిల్లా స్థాయి ఆధునీకరణ పురోగతి",
    today: "ఈరోజు",
    highConfidence: "అధిక ఖచ్చితత్వం",
    awaitingVerifier: "రెవెన్యూ అధికారి పరిశీలన కోసం వేచి ఉంది",
    ingestBtn: "కొత్త పత్రాన్ని అప్‌లోడ్ చేయండి",
    recordsProcessing: "ప్రాసెసింగ్‌లో ఉంది",
    complete: "పూర్తయింది",
    dashboardTab: "డాష్‌బోర్డ్",
    uploadTab: "అప్‌లోడ్",
    queueTab: "పరిశీలన లైను",
    gisTab: "మ్యాప్ / GIS",
  },
  kn: {
    welcome: "ಸುಸ್ವಾಗತ",
    subtitle: "ಎಐ ಆಧಾರಿತ ಭೂ ದಾಖಲೆಗಳ ಡಿಜಿಟಲೀಕರಣ ಪೋರ್ಟಲ್",
    totalDigitized: "ಒಟ್ಟು ಡಿಜಿಟಲೀಕರಿಸಿದ ದಾಖಲೆಗಳು",
    avgConfidence: "ಸರಾಸರಿ ನಿಖರತೆ ದರ",
    autoApproved: "ಸ್ವಯಂಚಾಲಿತ ಅನುಮೋದಿತ ದಾಖಲೆಗಳು",
    pendingQueue: "ಪರಿಶೀಲನೆಗೆ ಬಾಕಿ ಇದೆ",
    districtModernization: "ಜಿಲ್ಲಾವಾರು ಆಧುನಿಕೀಕರಣ ಪ್ರಗತಿ",
    today: "ಇಂದು ಸೇರಿಸಲಾಗಿದೆ",
    highConfidence: "ಹೆಚ್ಚಿನ ನಿಖರತೆ",
    awaitingVerifier: "ಕಂದಾಯ ಅಧಿಕಾರಿಯ ಪರಿಶೀಲನೆಗೆ ಕಾಯಲಾಗುತ್ತಿದೆ",
    ingestBtn: "ಹೊಸ ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    recordsProcessing: "ದಾಖಲೆ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ",
    complete: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    dashboardTab: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    uploadTab: "ಅಪ್‌ಲೋಡ್",
    queueTab: "ಪರಿಶೀಲನೆ ಸಾಲು",
    gisTab: "ನಕ್ಷೆ / GIS",
  },
  ml: {
    welcome: "സ്വാഗതം",
    subtitle: "എഐ അധിഷ്ഠിത ഭൂമി രേഖ ഡിജിറ്റൈസേഷൻ പോർട്ടൽ",
    totalDigitized: "ആകെ ഡിജിറ്റൈസ് ചെയ്ത രേഖകൾ",
    avgConfidence: "ശരാശരി കൃത്യത നിരക്ക്",
    autoApproved: "ഓട്ടോ-അംഗീകൃത രേഖകൾ",
    pendingQueue: "പരിശോധനയ്ക്കായി കാത്തിരിക്കുന്നു",
    districtModernization: "ജില്ലാതല ആധുനികവൽക്കരണ പുരോഗതി",
    today: "ഇന്ന് ചേർത്തത്",
    highConfidence: "ഉയർന്ന കൃത്യത",
    awaitingVerifier: "റവന്യൂ ഉദ്യോഗസ്ഥന്റെ അംഗീകാരത്തിനായി കാത്തിരിക്കുന്നു",
    ingestBtn: "പുതിയ രേഖ അപ്‌ലോഡ് ചെയ്യുക",
    recordsProcessing: "പ്രക്രിയയിൽ",
    complete: "പൂർത്തിയായി",
    dashboardTab: "ഡാഷ്‌ബോർഡ്",
    uploadTab: "അപ്‌ലോഡ്",
    queueTab: "പരിശോധനാ നിര",
    gisTab: "മാപ്പ് / GIS",
  },
  pa: {
    welcome: "ਜੀ ਆਇਆਂ ਨੂੰ",
    subtitle: "ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ ਡਿਜੀਟਾਈਜ਼ੇਸ਼ਨ ਪੋਰਟਲ",
    totalDigitized: "ਕੁੱਲ ਡਿਜੀਟਾਈਜ਼ਡ ਰਿਕਾਰਡ",
    avgConfidence: "ਔਸਤ ਸ਼ੁੱਧਤਾ ਦਰ",
    autoApproved: "ਸਵੈ-ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਰਿਕਾਰਡ",
    pendingQueue: "ਜਾਂਚ ਲਈ ਬਾਕੀ",
    districtModernization: "ਜ਼ਿਲ੍ਹਾ ਵਾਰ ਤਰੱਕੀ",
    today: "ਅੱਜ",
    highConfidence: "ਉੱਚ ਸ਼ੁੱਧਤਾ",
    awaitingVerifier: "ਮਾਲ ਅਫਸਰ ਦੀ ਉਡੀਕ",
    ingestBtn: "ਨਵਾਂ ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ",
    recordsProcessing: "ਪ੍ਰੋਸੈਸਿੰਗ ਅਧੀਨ",
    complete: "ਪੂਰਾ",
    dashboardTab: "ਡੈਸ਼ਬੋਰਡ",
    uploadTab: "ਅੱਪਲੋਡ",
    queueTab: "ਜਾਂਚ ਲਾਈਨ",
    gisTab: "ਨਕਸ਼ਾ / GIS",
  },
  or: {
    welcome: "ସ୍ୱାଗତ",
    subtitle: "ଏଆଇ ଆଧାରିତ ଜମି ରେକର୍ଡ ଡିଜିଟାଇଜେସନ୍ ପୋର୍ଟାଲ୍",
    totalDigitized: "ମୋଟ ଡିଜିଟାଇଜ୍ ହୋଇଥିବା ରେକର୍ଡ",
    avgConfidence: "ହାରାହାରି ସଠିକତା ହାର",
    autoApproved: "ସ୍ୱୟଂଚାଳିତ ଅନୁମୋଦିତ ରେକର୍ଡ",
    pendingQueue: "ଯାଞ୍ଚ ପାଇଁ ବାକି ଅଛି",
    districtModernization: "ଜିଲ୍ଲା ସ୍ତରୀୟ ଆଧୁନିକୀକରଣ ଅଗ୍ରଗତି",
    today: "ଆଜି",
    highConfidence: "ଉଚ୍ଚ ସଠିକତା",
    awaitingVerifier: "ରାଜସ୍ୱ ଅଧିକାରୀଙ୍କ ଅନୁମୋଦନ ଅପେକ୍ଷାରେ",
    ingestBtn: "ନୂତନ ଦଲିଲ ଅପଲୋଡ୍ କରନ୍ତୁ",
    recordsProcessing: "ପ୍ରକ୍ରିୟାଧୀନ",
    complete: "ସମ୍ପୂର୍ଣ୍ଣ",
    dashboardTab: "ଡ୍ୟାସବୋର୍ଡ",
    uploadTab: "ଅପଲୋଡ୍",
    queueTab: "ଯାଞ୍ଚ ଧାଡ଼ି",
    gisTab: "ମାନଚିତ୍ର / GIS",
  },
  as: {
    welcome: "পুনৰ স্বাগতম",
    subtitle: "কৃত্ৰিম বুদ্ধিমত্তা আধাৰিত ভূমি অভিলেখ ডিজিটাইজেচন পৰ্টেল",
    totalDigitized: "মুঠ ডিজিটাইজড অভিলেখ",
    avgConfidence: "গড় নিখুঁততাৰ হাৰ",
    autoApproved: "স্বয়ংক্ৰিয় অনুমোদিত অভিলেখ",
    pendingQueue: "সত্যানুসন্ধানৰ বাবে বাকী",
    districtModernization: "জিলা পর্যায়ৰ আধুনিকীকৰণৰ অগ্ৰগতি",
    today: "আজ যোগ দিয়া হৈছে",
    highConfidence: "উচ্চ নিখুঁততা",
    awaitingVerifier: "ৰাজহ বিষয়াৰ বাবে অপ অপেক্ষাৰত",
    ingestBtn: "নতুন নথি আপলোড কৰক",
    recordsProcessing: "অভিলেখ প্রক্রিয়াধীন",
    complete: "সম্পূৰ্ণ",
    dashboardTab: "ড্যাশবোর্ড",
    uploadTab: "আপলোড",
    queueTab: "যাচাইকৰণ",
    gisTab: "মানচিত্ৰ / GIS",
  },
  ur: {
    welcome: "خوش آمدید",
    subtitle: "زمین کا ریکارڈ ڈیجیٹائزیشن پورٹل",
    totalDigitized: "کل ڈیجیٹائزڈ ریکارڈز",
    avgConfidence: "اوسط درستگی کی شرح",
    autoApproved: "خودکار منظور شدہ ریکارڈز",
    pendingQueue: "تصدیق کے لیے زیر التواء",
    districtModernization: "ضلعی سطح کی ترقی",
    today: "آج",
    highConfidence: "اعلیٰ درستگی",
    awaitingVerifier: "ریونیو آفیسر کی تصدیق کا انتظار",
    ingestBtn: "نیا دستاویز اپ لوڈ کریں",
    recordsProcessing: "پروسیسنگ میں",
    complete: "مکمل",
    dashboardTab: "ڈیش بورڈ",
    uploadTab: "اپ لوڈ",
    queueTab: "تصدیق کی قطار",
    gisTab: "نقشہ / GIS",
  },
  sa: {
    welcome: "स्वागतम्",
    subtitle: "कृत्रिमबुद्धि-आधारितं भू-अभिलेख-अङ्कीकरण-जालस्थानम्",
    totalDigitized: "कुल अङ्कीकृताः अभिलेखाः",
    avgConfidence: "औसत शुद्धि-प्रतिशतम्",
    autoApproved: "स्वयमेव स्वीकृताः",
    pendingQueue: "परीक्षणार्थं अवशिष्टाः",
    districtModernization: "जनपदीय-प्रगतिः",
    today: "अद्य",
    highConfidence: "उच्च-शुद्धता",
    awaitingVerifier: "अधिकारिणः प्रतीक्षा",
    ingestBtn: "नवीनं पत्रं आरोपयतु",
    recordsProcessing: "प्रक्रियायाम्",
    complete: "पूर्णम्",
    dashboardTab: "मुख्यपृष्ठम्",
    uploadTab: "आरोपणम्",
    queueTab: "परीक्षणपङ्क्तिः",
    gisTab: "मानचित्रम् / GIS",
  },
  ks: {
    welcome: "ख़ैर मक़दम",
    subtitle: "ज़मीन रिकॉर्ड डिजिटाइज़ेशन पोर्टल",
    totalDigitized: "कुल डिजिटाइज़्ड रिकॉर्ड",
    avgConfidence: "औसत सटीकता",
    autoApproved: "खुद-ब-खुद मंज़ूर",
    pendingQueue: "जांच ली बाकी",
    districtModernization: "ज़िला तरक्की",
    today: "अज़",
    highConfidence: "उच्च सटीकता",
    awaitingVerifier: "अफ़सर सुंद इंतज़ार",
    ingestBtn: "नया रिकॉर्ड अपलोड करिव",
    recordsProcessing: "प्रोसेसिंग मंज़",
    complete: "मुकम्मल",
    dashboardTab: "डैशबोर्ड",
    uploadTab: "अपलोड",
    queueTab: "जांच कतार",
    gisTab: "नक्शा / GIS",
  },
  sd: {
    welcome: "ڀلي ڪري آيا",
    subtitle: "زمين ريڪارڊ ڊجيٽائيزيشن پورٽل",
    totalDigitized: "ڪل ڊجيٽائيزڊ ريڪارڊ",
    avgConfidence: "سراسري درستگي",
    autoApproved: "خودڪار منظور ٿيل",
    pendingQueue: "پڙتال لاءِ باقي",
    districtModernization: "ضلعي تريقي",
    today: "आज",
    highConfidence: "اعليٰ درستگي",
    awaitingVerifier: "آفيسر جي انتظار",
    ingestBtn: "نئون ريڪارڊ اپلوڊ ڪريو",
    recordsProcessing: "پروسيسنگ ۾",
    complete: "مکمل",
    dashboardTab: "ڊئش بورڊ",
    uploadTab: "اپ لوڊ",
    queueTab: "پڙتال قطار",
    gisTab: "نقشو / GIS",
  },
  ne: {
    welcome: "स्वागत छ",
    subtitle: "एआई आधारित जग्गा अभिलेख डिजिटलीकरण पोर्टल",
    totalDigitized: "कुल डिजिटाइज्ड अभिलेख",
    avgConfidence: "औसत शुद्धता दर",
    autoApproved: "स्वचालित स्वीकृत अभिलेख",
    pendingQueue: "छानबिनको लागि बाँकी",
    districtModernization: "जिल्ला स्तरको आधुनिकीकरण प्रगति",
    today: "आज",
    highConfidence: "उच्च शुद्धता",
    awaitingVerifier: "मालपोत अधिकृतको प्रतीक्षामा",
    ingestBtn: "नयाँ कागजात अपलोड गर्नुहोस्",
    recordsProcessing: "प्रक्रियामा",
    complete: "सम्पन्न",
    dashboardTab: "मुख्य पृष्ठ",
    uploadTab: "अपलोड",
    queueTab: "जाँच कतार",
    gisTab: "मानचित्र / GIS",
  },
  kok: {
    welcome: "येयात, येयात",
    subtitle: "जमीन रिकॉर्ड डिजिटायझेशन पोर्टल",
    totalDigitized: "वट्ट डिजिटाईज्ड रिकॉर्ड्स",
    avgConfidence: "सरासरी अचूकता",
    autoApproved: "स्वयंचलित मानयता",
    pendingQueue: "तपासा खातीर उरिल्ले",
    districtModernization: "जिल्हो प्रगती",
    today: "आयज",
    highConfidence: "अत्यंत अचूक",
    awaitingVerifier: "महसूल अधिकार्याची वाट",
    ingestBtn: "नवो दाखलो अपलोड करात",
    recordsProcessing: "प्रक्रियेत आसा",
    complete: "पूर्ण",
    dashboardTab: "मुखेल पान",
    uploadTab: "अपलोड",
    queueTab: "तपासणी",
    gisTab: "नकाशो / GIS",
  },
  doi: {
    welcome: "जी आया नूं",
    subtitle: "जमीन रिकार्ड डिजिटलीकरण पोर्टल",
    totalDigitized: "कुल डिजिटाइज़्ड रिकार्ड",
    avgConfidence: "औसत सटीकता",
    autoApproved: "खुद-ब-खुद मंज़ूर",
    pendingQueue: "जांच ली बाकी",
    districtModernization: "जिला प्रगति",
    today: "अज्ज",
    highConfidence: "उच्च सटीकता",
    awaitingVerifier: "अफ़सर दा इंतज़ार",
    ingestBtn: "नवा रिकार्ड अपलोड करो",
    recordsProcessing: "प्रोसेसिंग च",
    complete: "पूरा",
    dashboardTab: "डैशबोर्ड",
    uploadTab: "अपलोड",
    queueTab: "जांच",
    gisTab: "नक्शा / GIS",
  },
  mni: {
    welcome: "तरामना ओकचरी",
    subtitle: "लामगी रेकॉर्ड डिजिटाइजेसन पोर्तल",
    totalDigitized: "पुन्ना डिजिटाइज तौख्राबा रेकॉर्ड",
    avgConfidence: "चांगचत्की अचुमबा",
    autoApproved: "ईशाना याबा",
    pendingQueue: "येसिनबा ङाइरिबा",
    districtModernization: "जिलागी चाओखत्पा",
    today: "ङसि",
    highConfidence: "अवाङ्बा अचुमबा",
    awaitingVerifier: "ओफिसारगी ङाइरिबा",
    ingestBtn: "अनौबा रेकॉर्ड हप्पु",
    recordsProcessing: "प्रसेस तौइरिबा",
    complete: "लोइख्रे",
    dashboardTab: "मयाइशाङ",
    uploadTab: "हप्पु",
    queueTab: "येसिनबा",
    gisTab: "मौनफम / GIS",
  },
  sat: {
    welcome: "ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ",
    subtitle: "ᱦᱟᱥᱟ ᱨᱮᱠᱚᱨᱰ ᱰᱤᱡᱤᱴᱟᱞ ᱯᱚᱨᱴᱟᱞ",
    totalDigitized: "ᱡᱚᱛᱚ ᱰᱤᱡᱤᱴᱟᱞ ᱨᱮᱠᱚᱨᱰ",
    avgConfidence: "ᱥᱟᱹᱨᱤ ᱠᱟᱛᱷᱟ",
    autoApproved: "ᱟᱯᱱᱟᱨ ᱛᱮ ᱥᱟᱹᱨᱤ",
    pendingQueue: "ᱵᱤ central",
    districtModernization: "ᱡᱤᱞᱟᱹ ᱞᱟᱦᱟᱱᱛᱤ",
    today: "ᱛᱮᱦᱮᱧ",
    highConfidence: "ᱪᱮᱛᱟᱱ ᱥᱟᱹᱨᱤ",
    awaitingVerifier: "ᱚᱯᱷᱤᱥᱚᱨ ᱛᱟᱺᱜᱤ",
    ingestBtn: "ᱱᱟᱶᱟ ᱥᱟᱠᱟᱢ ᱟᱯᱞᱚᱰ",
    recordsProcessing: "ᱠᱟᱹᱢᱤ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ",
    complete: "ᱯᱩᱨᱟᱹᱣ",
    dashboardTab: "ᱢᱩᱬᱩᱛ",
    uploadTab: "ᱟᱯᱞᱚᱰ",
    queueTab: "ᱵᱤ central",
    gisTab: "ᱱᱚᱠᱥᱟ / GIS",
  },
  brx: {
    welcome: "बहाइबाय",
    subtitle: "हायारि लेखाDigitization प्रणालि",
    totalDigitized: "गासै डिजिटाइज खालामनाय लेखा",
    avgConfidence: "गदनाय रोखोम",
    autoApproved: "गावखौनो गनायथि होनाय",
    pendingQueue: "नेनानै थानाय",
    districtModernization: "जिल्ला जौगानाय",
    today: "दिनै फरायनाय",
    highConfidence: "गोजौ रोखोम",
    awaitingVerifier: "आफिसारनि नेनाय",
    ingestBtn: "गोदान लेखा थिसन",
    recordsProcessing: "प्रक्रियायाव थानाय",
    complete: "आबुं",
    dashboardTab: "गुबै",
    uploadTab: "थिसन",
    queueTab: "नेनाय",
    gisTab: "मानचित्र / GIS",
  },
  mai: {
    welcome: "स्वागत अछि",
    subtitle: "एआई आधारित भूमि अभिलेख डिजिटलीकरण पोर्टल",
    totalDigitized: "कुल डिजिटाइज़्ड अभिलेख",
    avgConfidence: "औसत सटीकता",
    autoApproved: "स्वचालित स्वीकृत",
    pendingQueue: "जांच हेतु लंबित",
    districtModernization: "जिला स्तरीय प्रगति",
    today: "आइ",
    highConfidence: "उच्च सटीकता",
    awaitingVerifier: "अधिकारीक प्रतीक्षा",
    ingestBtn: "नवीन दस्तावेज अपलोड करू",
    recordsProcessing: "प्रक्रियामे",
    complete: "पूर्ण",
    dashboardTab: "मुख्य पृष्ठ",
    uploadTab: "अपलोड",
    queueTab: "सत्यापन",
    gisTab: "मानचित्र / GIS",
  }
}

export function t(key, langCode = 'mr') {
  const langDict = UI_TRANSLATIONS[langCode] || UI_TRANSLATIONS['mr'] || UI_TRANSLATIONS['en']
  return langDict[key] || UI_TRANSLATIONS['en'][key] || key
}
