/*
Official 22 Languages of India (8th Schedule of the Constitution) + English
*/

export const CONSTITUTION_22_LANGUAGES = [
  { code: 'mr', nameEn: 'Marathi', nameNative: 'मराठी', icon: '🚩', script: 'Devanagari' },
  { code: 'hi', nameEn: 'Hindi', nameNative: 'हिन्दी', icon: '🇮🇳', script: 'Devanagari' },
  { code: 'en', nameEn: 'English', nameNative: 'English', icon: '🇬🇧', script: 'Latin' },
  { code: 'bn', nameEn: 'Bengali', nameNative: 'বাংলা', icon: '🇧🇩', script: 'Bengali' },
  { code: 'gu', nameEn: 'Gujarati', nameNative: 'ગુજરાતી', icon: '🏛️', script: 'Gujarati' },
  { code: 'ta', nameEn: 'Tamil', nameNative: 'தமிழ்', icon: '🏛️', script: 'Tamil' },
  { code: 'te', nameEn: 'Telugu', nameNative: 'తెలుగు', icon: '🏛️', script: 'Telugu' },
  { code: 'kn', nameEn: 'Kannada', nameNative: 'ಕನ್ನಡ', icon: '🏛️', script: 'Kannada' },
  { code: 'ml', nameEn: 'Malayalam', nameNative: 'മലയാളം', icon: '🏛️', script: 'Malayalam' },
  { code: 'pa', nameEn: 'Punjabi', nameNative: 'ਪੰਜਾਬੀ', icon: '🏛️', script: 'Gurmukhi' },
  { code: 'or', nameEn: 'Odia', nameNative: 'ଓଡ଼ିଆ', icon: '🏛️', script: 'Odia' },
  { code: 'as', nameEn: 'Assamese', nameNative: 'অসমীয়া', icon: '🏛️', script: 'Bengali-Assamese' },
  { code: 'ur', nameEn: 'Urdu', nameNative: 'اردو', icon: '🏛️', script: 'Perso-Arabic' },
  { code: 'sa', nameEn: 'Sanskrit', nameNative: 'संस्कृतम्', icon: '🕉️', script: 'Devanagari' },
  { code: 'ks', nameEn: 'Kashmiri', nameNative: 'कॉशुर', icon: '🏔️', script: 'Perso-Arabic/Devanagari' },
  { code: 'sd', nameEn: 'Sindhi', nameNative: 'सिन्धी', icon: '🏛️', script: 'Perso-Arabic/Devanagari' },
  { code: 'ne', nameEn: 'Nepali', nameNative: 'नेपाली', icon: '🏔️', script: 'Devanagari' },
  { code: 'kok', nameEn: 'Konkani', nameNative: 'कोंकणी', icon: '🏖️', script: 'Devanagari' },
  { code: 'doi', nameEn: 'Dogri', nameNative: 'डोगरी', icon: '🏛️', script: 'Devanagari' },
  { code: 'mni', nameEn: 'Manipuri', nameNative: 'মইतैलोन', icon: '🏛️', script: 'Meitei/Bengali' },
  { code: 'sat', nameEn: 'Santali', nameNative: 'ᱥᱟᱱᱛᱟᱲᱤ', icon: '🏛️', script: 'Ol Chiki' },
  { code: 'brx', nameEn: 'Bodo', nameNative: 'बर\'', icon: '🏛️', script: 'Devanagari' },
  { code: 'mai', nameEn: 'Maithili', nameNative: 'मैथिली', icon: '🏛️', script: 'Devanagari' },
]

export function getLanguageByCode(code) {
  return CONSTITUTION_22_LANGUAGES.find((l) => l.code === code) || CONSTITUTION_22_LANGUAGES[0]
}

export const UI_TRANSLATIONS = {
  mr: {
    headerGovIndia: "🇮🇳 भारत सरकार | Govt. of India",
    headerDept: "महाराष्ट्र शासन - महसूल व वन विभाग",
    headerTitle: "भूनेत्रा - राज्य भूमी अभिलेख संगणकीकरण प्रणाली",
    roleTag: "पद (Role):",
    roleOfficer: "तहसीलदार (Revenue Officer)",
    roleVerifier: "तलाठी (Field Verifier)",
    roleAdmin: "प्रशासक (Admin)",
    roleCivilian: "नागरिक (Citizen)",
    officerLoginBtn: "अधिकारी लॉगिन",
    citizenBadge: "नागरिक भूमी अभिलेख पोर्टल (DILRMP Gateway)",
    citizenPortalTitle: "डिजिटल महसूल अभिलेख सेवा (Public Land Records)",
    citizenPortalSubtitle: "आपला आवश्यक भूमी दस्तऐवज निवडा, प्रमाणित अभिलेख शोधा किंवा एआय तंत्रज्ञानाद्वारे सत्यता पडताळणी करा.",
    step1DocType: "पायरी १: दस्तऐवजाचा प्रकार निवडा (Step 1: Select Document Type)",
    step2GeoSearch: "पायरी २: भौगोलिक स्थान व शोध तपशील (Step 2: Geographic Hierarchy & Search)",
    selectedDocBadge: "निवडलेला दस्तऐवज:",
    selectDistrict: "जिल्हा निवडा (District)",
    selectTaluka: "तालुका निवडा (Taluka)",
    selectVillage: "गाव निवडा (Village)",
    searchRecordsBtn: "अभिलेख शोधा (Search Record)",
    searchingBtn: "शोधत आहे... (Searching...)",
    searchPlaceholder: "गट / सर्व्हे / खाते क्रमांक टाका (Enter Survey / Khata No.)",
    ownerNamePlaceholder: "खातेदाराचे / अर्जदाराचे नाव (Citizen Name - Optional)",
    searchTab: "अभिलेख शोध (Search)",
    verifyCopyTab: "AI दस्तऐवज पडताळणी (Verify Copy)",
    mutationStatusTab: "फेरफार अर्ज स्थिती (Mutation Status)",
    docType712Title: "गाव नमुना ७/१२ उतारा (Form 7/12 Extract)",
    docType712Desc: "उतारा, गट/सर्व्हे क्रमांक, भोगवटादार हक्क व पीक पाहणी तपशील",
    docType8ATitle: "गाव नमुना ८-अ खाते नोंद (Form 8-A Extract)",
    docType8ADesc: "खातेदाराकडील सर्व जमिनींचे एकत्रित क्षेत्र व शासकीय आकारणी",
    docTypePropertyCardTitle: "मालमत्ता पत्रक (City Survey Property Card)",
    docTypePropertyCardDesc: "शहरी व गावठाण भागातील मिळकत पत्रिका व नगर भूमापन नोंद",
    docTypeFerfarTitle: "गाव नमुना ६ फेरफार (Mutation Register / Ferfar)",
    docTypeFerfarDesc: "वारस नोंद, खरेदीखत, बक्षीसपत्र व हक्क बदलांची ऐतिहासिक नोंद",
    docTypeSaleDeedTitle: "नोंदणीकृत खरेदीखत (Registered Sale Deed)",
    docTypeSaleDeedDesc: "दुय्यम निबंधक कार्यालयातील नोंदणीकृत खरेदीखत व मुद्रांक शुल्क",
    docTypeSearchReportTitle: "बोजा प्रमाणपत्र व शोध अहवाल (Encumbrance & Search)",
    docTypeSearchReportDesc: "३०-वर्षीय कायदेशीर शोध अहवाल, बँक तारण व दायित्व प्रमाणपत्र",
    docTypeGatMapTitle: "गट नकाशा व मोजणी प्रत (Cadastral Survey Map)",
    docTypeGatMapDesc: "जमीन सीमांकन नकाशा, टिपण व प्रत्यक्ष भूमापन मोजणी प्रत",
    docTypeNaOrderTitle: "अकृषिक आदेश व सनद (NA Conversion Sanad)",
    docTypeNaOrderDesc: "जिल्हाधिकारी अकृषिक परवानगी आदेश (NA 44) व अकृषिक सनद",
    docTypeGiftDeedTitle: "बक्षीसपत्र व हक्कसोडपत्र (Gift & Relinquishment)",
    docTypeGiftDeedDesc: "कुटुंबातील सदस्यांमधील विनामोबदला बक्षीसपत्र व हक्कसोड नोंदणी",
    docTypePartitionTitle: "वारस नोंद व वाटपपत्र (Partition & Heirship)",
    docTypePartitionDesc: "तहसीलदार वारस चौकशी नोंद व कुटुंबातील हिस्सा वाटपपत्र दस्त",
    gatNoLabel: "गट क्र.",
    khataNoLabel: "खाते क्र.",
    downloadCertifiedPdfBtn: "📜 अधिकृत प्रमाणपत्र डाउनलोड करा (22 Languages)",
    verifiedStateRecordBadge: "✔ प्रमाणित राज्य भूमि अभिलेख",
    digitallySignedGuarantee: "डिजिटल स्वाक्षरित ७/१२ — महाराष्ट्र शासन महसूल विभाग (NIC/DILRMP)",
    ownerNameLabel: "खातेदाराचे नाव (Owner Name)",
    landAreaLabel: "एकूण क्षेत्र (Total Area)",
    ownershipTypeLabel: "धारणा प्रकार (Tenure Type)",
    liensLabel: "इतर हक्क व कर्ज बोजा (Liens & Encumbrances)",
    uploadDocTab: "📄 दस्तावेज अपलोड",
    welcome: "पुन्हा स्वागत आहे",
    subtitle: "कृत्रिम बुद्धिमत्ता आधारित भूमी अभिलेख संगणकीकरण प्रणाली",
    totalDigitized: "एकूण डिजिटाईज्ड अभिलेख",
    avgConfidence: "सरासरी अचूकता दर",
    autoApproved: "स्वायत्त स्वीकृत अभिलेख",
    pendingQueue: "महसूल पडताळणी प्रलंबित",
    districtModernization: "जिल्हास्तरीय संगणकीकरण प्रगती",
    today: "आज जोडले",
    highConfidence: "उच्च अचूकता दर",
    awaitingVerifier: "तलाठी/तहसीलदार पडताळणी प्रलंबित",
    ingestBtn: "नवीन दस्तावेज अपलोड करा",
    recordsProcessing: "अभिलेख प्रक्रियेत",
    complete: "पूर्ण",
    dashboardTab: "डॅशबोर्ड",
    exploreTab: "एक्सप्लोर करा",
    citizenTab: "नागरिक सेवा",
    uploadTab: "दस्तऐवज अपलोड",
    queueTab: "महसूल पडताळणी",
    gisTab: "नकाशा / GIS",
    verWorkspaceTitle: "पडताळणी कार्यस्थळ व ओसीआर तपासणी",
    verWorkspaceSubtitle: "मूळ स्कॅन केलेल्या दस्तऐवजाशी काढलेल्या मजकुराची पडताळणी करा.",
    ocrOverlaysBtn: "ओसीआर बॉक्सेस",
    rawScanBtn: "मूळ स्कॅन",
    textLayerBtn: "मजकूर स्तर",
    forensicElaBadge: "फॉरेन्सिक ईएलए व सत्यता तपासणी",
    approveSaveBtn: "मंजूर करा व जतन करा",
    approvedLoggedBtn: "मंजूर व नोंदणीकृत",
    resetEditsBtn: "बदल पूर्ववत करा",
    module3Title: "विभाग ३ · मानवी पडताळणी ओसीआर वर्कस्पेस",
    assignedVerifier: "नियुक्त पडताळणी अधिकारी",
    docSelectorLabel: "दस्तऐवज:",
    extractedDataVerificationTitle: "काढलेल्या माहितीची पडताळणी",
    imageElaCheckLabel: "प्रतिमा ईएलए छेडछाड तपासणी",
    mutationLedgerLabel: "फेरफार नोंद मिलान",
    villageCollisionLabel: "गाव दावा टकराव तपासणी",
    villageAndCodeLabel: "गाव (Village) व कोड",
    khasraNumberLabel: "गट / सर्व्हे क्रमांक (Khasra No.)",
    flaggedForReviewLabel: "पुनरावलोकनासाठी चिन्हांकित",
    ocrHighlightHint: "या इनपुटवर क्लिक केल्यास मूळ दस्तऐवजावरील संबंधित ओसीआर बॉक्स हायलाइट होतो.",
    verNotesLabel: "पडताळणी टिप्पण्या / ऑडिट शेरा",
    verNotesPlaceholder: "क्षेत्र दुरुस्ती किंवा सत्यापन ऑडिटसाठी कारण नोंदवा...",
    uploadSectionTitle: "भूमी अभिलेख दस्तऐवज अपलोड",
    uploadSectionSubtitle: "अचूक ओसीआर आणि स्कीमा मॅपिंगद्वारे जुन्या महसूल कागदपत्रांचे डिजिटायझेशन करा.",
    dragDropTitle: "स्कॅन केलेला भूमी दस्तऐवज येथे ड्रॅग आणि ड्रॉप करा",
    dragDropSub: "किंवा आपल्या डिव्हाइसवरून निवडण्यासाठी क्लिक करा",
    supportedFormats: "समर्थित स्वरूपे: PDF, TIFF, JPG, PNG (कमाल ५०MB)",
    docCategoryLabel: "दस्तऐवज प्रवर्ग",
    districtScopeLabel: "जिल्हा व्याप्ती",
    primaryLanguageLabel: "प्राथमिक भाषा / OCR",
    startAiPipelineBtn: "एआय डिजिटायझेशन सुरू करा",
    executingAiPipelineBtn: "एआय प्रक्रिया सुरू आहे...",
    pipelineLiveStatusTitle: "पाइपलाइन थेट स्थिती",
    overallProgressLabel: "एकूण प्रगती",
    stepStorage: "सुरक्षित स्टोरेज संचयन",
    stepOcr: "बहुभाषिक ओसीआर",
    stepStructuring: "एलएलएम स्कीमा रचना",
    stepValidation: "अंतिम पडताळणी",
  },
  hi: {
    headerGovIndia: "🇮🇳 भारत सरकार | Govt. of India",
    headerDept: "महाराष्ट्र सरकार - राजस्व एवं वन विभाग",
    headerTitle: "भूनेत्र - राज्य भूमि अभिलेख डिजिटलीकरण प्रणाली",
    roleTag: "पद (Role):",
    roleOfficer: "तहसीलदार (Revenue Officer)",
    roleVerifier: "पटवारी / तलाठी (Field Verifier)",
    roleAdmin: "प्रशासक (Admin)",
    roleCivilian: "नागरिक (Citizen)",
    officerLoginBtn: "अधिकारी लॉगिन",
    citizenBadge: "नागरिक भूमि अभिलेख पोर्टल (DILRMP Gateway)",
    citizenPortalTitle: "डिजिटल राजस्व अभिलेख सेवा (Public Land Records)",
    citizenPortalSubtitle: "वांछित भूमि दस्तावेज चुनें, सत्यापित रिकॉर्ड खोजें अथवा एआई तकनीक से सत्यता प्रमाणित करें।",
    step1DocType: "चरण १: दस्तावेज का प्रकार चुनें (Step 1: Select Document Type)",
    step2GeoSearch: "चरण २: भौगोलिक स्थान एवं खोज विवरण (Step 2: Geographic Search)",
    selectedDocBadge: "चयनित दस्तावेज:",
    selectDistrict: "जिला चुनें (District)",
    selectTaluka: "तहसील / तालुका चुनें (Taluka)",
    selectVillage: "गांव चुनें (Village)",
    searchRecordsBtn: "अभिलेख खोजें (Search Record)",
    searchingBtn: "खोज जारी है... (Searching...)",
    searchPlaceholder: "गट / खसरा / खाता संख्या दर्ज करें (Enter Survey / Khata No.)",
    ownerNamePlaceholder: "खातेदार / आवेदक का नाम (Citizen Name - Optional)",
    searchTab: "अभिलेख खोज (Search)",
    verifyCopyTab: "AI दस्तावेज सत्यापन (Verify Copy)",
    mutationStatusTab: "नामांतरण स्थिति (Mutation Status)",
    docType712Title: "गांव नमूना ७/१२ खसरा खतौनी (Form 7/12 Extract)",
    docType712Desc: "उतारा, गट/खसरा संख्या, खातेदार अधिकार एवं फसल विवरण",
    docType8ATitle: "गांव नमूना ८-अ खाता बही (Form 8-A Extract)",
    docType8ADesc: "खातेदार की सभी भूमियों का कुल रकबा एवं राजस्व निर्धारण",
    docTypePropertyCardTitle: "संपत्ति पत्रक (City Survey Property Card)",
    docTypePropertyCardDesc: "शहरी एवं आबादी क्षेत्र का नगर भूमापन संपत्ति रिकॉर्ड",
    docTypeFerfarTitle: "नामांतरण पंजी (Mutation Register / Ferfar)",
    docTypeFerfarDesc: "विरासत, बैनामा, दानपत्र एवं अधिकारों के परिवर्तन का इतिहास",
    docTypeSaleDeedTitle: "पंजीकृत बैनामा (Registered Sale Deed)",
    docTypeSaleDeedDesc: "उप-पंजीयक कार्यालय का पंजीकृत विक्रय विलेख एवं स्टांप शुल्क",
    docTypeSearchReportTitle: "भार प्रमाणपत्र व शोध रिपोर्ट (Encumbrance & Search)",
    docTypeSearchReportDesc: "३०-वर्षीय विधिक स्वामित्व जांच, बैंक बंधक एवं भार मुक्ति रिपोर्ट",
    docTypeGatMapTitle: "भूकर मानचित्र व पैमाइश (Cadastral Survey Map)",
    docTypeGatMapDesc: "खसरा सीमांकन नक्शा, टीपन एवं धरातलीय भू-मापन प्रति",
    docTypeNaOrderTitle: "अकृषि आदेश व सनद (NA Conversion Sanad)",
    docTypeNaOrderDesc: "जिलाधिकारी अकृषि अनुमति आदेश (धारा 44) व अकृषि सनद",
    docTypeGiftDeedTitle: "दानपत्र व हकत्याग विलेख (Gift & Relinquishment)",
    docTypeGiftDeedDesc: "पारिवारिक सदस्यों के मध्य बिना प्रतिफल दानपत्र व हकत्याग पंजीयन",
    docTypePartitionTitle: "विरासत व पारिवारिक बंटवारा (Partition & Heirship)",
    docTypePartitionDesc: "तहसीलदार विरासत जांच आदेश एवं विधिक उत्तराधिकारी बंटवारा पत्र",
    gatNoLabel: "गट सं.",
    khataNoLabel: "खाता सं.",
    downloadCertifiedPdfBtn: "📜 प्रमाणित प्रमाणपत्र डाउनलोड करें (22 Languages)",
    verifiedStateRecordBadge: "✔ सत्यापित राज्य भूमि अभिलेख",
    digitallySignedGuarantee: "डिजिटल हस्ताक्षरित ७/१२ — महाराष्ट्र सरकार राजस्व विभाग",
    ownerNameLabel: "खातेदार का नाम (Owner Name)",
    landAreaLabel: "कुल क्षेत्र (Total Area)",
    ownershipTypeLabel: "धारण प्रकार (Tenure Type)",
    liensLabel: "अन्य अधिकार व ऋण बोझ (Liens & Encumbrances)",
    uploadDocTab: "📄 दस्तावेज अपलोड",
    welcome: "पुनः स्वागत है",
    subtitle: "कृत्रिम बुद्धिमत्ता आधारित भूमि अभिलेख डिजिटलीकरण एवं निगरानी पोर्टल",
    totalDigitized: "कुल डिजिटाइज़्ड अभिलेख",
    avgConfidence: "औसत सटीकता दर",
    autoApproved: "स्वायत्त स्वीकृत रिकॉर्ड्स",
    pendingQueue: "समीक्षा हेतु लंबित",
    districtModernization: "जिला स्तरीय आधुनिकीकरण प्रगति",
    today: "आज जोड़े गए",
    highConfidence: "उच्च सटीकता",
    awaitingVerifier: "राजस्व अधिकारी सत्यापन हेतु लंबित",
    ingestBtn: "नया दस्तावेज अपलोड करें",
    recordsProcessing: "रिकॉर्ड्स प्रसंस्करण में",
    complete: "पूर्ण",
    dashboardTab: "डैशबोर्ड",
    exploreTab: "एक्सप्लोर करें",
    citizenTab: "नागरिक पोर्टल",
    uploadTab: "दस्तावेज अपलोड",
    queueTab: "राजस्व सत्यापन",
    gisTab: "मानचित्र / GIS",
    verWorkspaceTitle: "सत्यापन कार्यक्षेत्र एवं ओसीआर निरीक्षण",
    verWorkspaceSubtitle: "मूल स्कैन किए गए दस्तावेज के साथ निकाले गए डेटा का मिलान करें।",
    ocrOverlaysBtn: "ओसीआर बॉक्स",
    rawScanBtn: "मूल स्कैन",
    textLayerBtn: "पाठ स्तर",
    forensicElaBadge: "फोरेंसिक ईएलए एवं सत्यता विश्लेषण",
    approveSaveBtn: "स्वीकृत करें एवं सहेजें",
    approvedLoggedBtn: "सत्यापित एवं पंजीकृत",
    resetEditsBtn: "संशोधन पूर्ववत करें",
    module3Title: "मॉड्यूल ३ · मानव-हस्तक्षेप ओसीआर सत्यापन",
    assignedVerifier: "नियुक्त सत्यापनकर्ता",
    docSelectorLabel: "दस्तावेज:",
    extractedDataVerificationTitle: "निकाले गए डेटा का सत्यापन",
    imageElaCheckLabel: "छवि ईएलए छेड़छाड़ जांच",
    mutationLedgerLabel: "नामांतरण बही मिलान",
    villageCollisionLabel: "ग्राम दावा टकराव जांच",
    villageAndCodeLabel: "गांव (Village) एवं कोड",
    khasraNumberLabel: "खसरा / गट संख्या (Khasra No.)",
    flaggedForReviewLabel: "समीक्षा हेतु चिह्नित",
    ocrHighlightHint: "इस फ़ील्ड पर क्लिक करने से मूल दस्तावेज़ पर संबंधित ओसीआर बॉक्स हाइलाइट होता है।",
    verNotesLabel: "सत्यापन टिप्पणियां / ऑडिट टिप्पणी",
    verNotesPlaceholder: "फ़ील्ड सुधार अथवा सत्यापन ऑडिट का कारण दर्ज करें...",
    uploadSectionTitle: "भूमि अभिलेख दस्तावेज अपलोड",
    uploadSectionSubtitle: "उच्च-सटीक ओसीआर और स्कीमा मैपिंग के साथ पुराने भूमि दस्तावेजों का डिजिटलीकरण करें।",
    dragDropTitle: "स्कैन किया गया भूमि दस्तावेज यहां ड्रैग और ड्रॉप करें",
    dragDropSub: "अथवा अपनी डिवाइस से चुनने के लिए क्लिक करें",
    supportedFormats: "समर्थित प्रारूप: PDF, TIFF, JPG, PNG (अधिकतम 50MB)",
    docCategoryLabel: "दस्तावेज श्रेणी",
    districtScopeLabel: "जिला दायरा",
    primaryLanguageLabel: "प्राथमिक भाषा / OCR",
    startAiPipelineBtn: "एआई डिजिटलीकरण प्रारंभ करें",
    executingAiPipelineBtn: "एआई पाइपलाइन निष्पादित हो रही है...",
    pipelineLiveStatusTitle: "पाइपलाइन लाइव स्थिति",
    overallProgressLabel: "कुल प्रगति",
    stepStorage: "सुरक्षित स्टोरेज संग्रहण",
    stepOcr: "बहुभाषी ओसीआर",
    stepStructuring: "एलएलएम स्कीमा संरचना",
    stepValidation: "अंतिम सत्यापन",
  },
  en: {
    headerGovIndia: "🇮🇳 Govt. of India",
    headerDept: "Govt. of Maharashtra - Revenue & Forest Dept.",
    headerTitle: "BHUNETRA - State Land Records Modernization System",
    roleTag: "Role:",
    roleOfficer: "Revenue Officer",
    roleVerifier: "Field Verifier",
    roleAdmin: "Administrator",
    roleCivilian: "Citizen / Civilian",
    officerLoginBtn: "Officer Login",
    citizenBadge: "Citizen Land Records Portal (DILRMP Gateway)",
    citizenPortalTitle: "Public Land Records Modernization Service",
    citizenPortalSubtitle: "Select your desired land record document type, query official registry archives, or verify scanned copies with sovereign AI.",
    step1DocType: "Step 1: Select Document Type",
    step2GeoSearch: "Step 2: Geographic Hierarchy & Search Parameters",
    selectedDocBadge: "Selected Document:",
    selectDistrict: "Select District",
    selectTaluka: "Select Taluka / Tehsil",
    selectVillage: "Select Village",
    searchRecordsBtn: "Search Land Records",
    searchingBtn: "Searching Registry...",
    searchPlaceholder: "Enter Survey / Gat / Khata Number...",
    ownerNamePlaceholder: "Citizen / Landowner Name (Optional)",
    searchTab: "Search Records",
    verifyCopyTab: "AI Document Verification",
    mutationStatusTab: "Mutation Application Status",
    docType712Title: "Village Form 7/12 Extract (७/१२ उतारा)",
    docType712Desc: "Survey/Gat parcel rights, landholder classification & seasonal crop inspection",
    docType8ATitle: "Village Form 8-A Khata Sheet (८-अ खाते नोंद)",
    docType8ADesc: "Consolidated holding ledger across all survey numbers & land revenue assessment",
    docTypePropertyCardTitle: "City Survey Property Card (मालमत्ता पत्रक)",
    docTypePropertyCardDesc: "Urban municipal parcel ownership, CTS number & building rights ledger",
    docTypeFerfarTitle: "Mutation Register Extract (गाव नमुना ६ फेरफार)",
    docTypeFerfarDesc: "Certified title transfers, inheritance updates & registered mutation history",
    docTypeSaleDeedTitle: "Registered Sale Deed (खरेदीखत दस्तऐवज)",
    docTypeSaleDeedDesc: "Sub-registrar conveyance deed registration, stamp duty & consideration",
    docTypeSearchReportTitle: "Encumbrance & Search Report (शोध अहवाल)",
    docTypeSearchReportDesc: "30-year advocate title opinion, bank mortgage charge & non-encumbrance cert",
    docTypeGatMapTitle: "Cadastral Survey Map / Tipan (गट नकाशा)",
    docTypeGatMapDesc: "Official geometric boundary map, physical coordinates & survey measurements",
    docTypeNaOrderTitle: "NA Conversion Order & Sanad (अकृषिक सनद)",
    docTypeNaOrderDesc: "District Collector non-agricultural conversion order (Sec 44) and Sanad",
    docTypeGiftDeedTitle: "Gift & Relinquishment Deed (बक्षीस / हक्कसोड)",
    docTypeGiftDeedDesc: "Intra-family gratuitous conveyance deed & registered co-owner release",
    docTypePartitionTitle: "Partition Deed & Heirship (वारस नोंद व वाटप)",
    docTypePartitionDesc: "Tahsildar legal heirship certification and registered family partition deed",
    gatNoLabel: "Gat / Survey No.",
    khataNoLabel: "Khata No.",
    downloadCertifiedPdfBtn: "📜 Download Certified PDF (22 Languages)",
    verifiedStateRecordBadge: "✔ VERIFIED STATE LAND RECORD",
    digitallySignedGuarantee: "Digitally Signed Extract — Govt. of Maharashtra Revenue Dept. (NIC/DILRMP)",
    ownerNameLabel: "Landholder / Owner Name",
    landAreaLabel: "Total Land Area",
    ownershipTypeLabel: "Tenure Classification",
    liensLabel: "Active Liens & Encumbrances",
    uploadDocTab: "📄 Upload Document",
    welcome: "Welcome back",
    subtitle: "AI-assisted land record digitization and monitoring portal",
    totalDigitized: "TOTAL RECORDS DIGITIZED",
    avgConfidence: "AVERAGE CONFIDENCE",
    autoApproved: "AUTO-APPROVED RECORDS",
    pendingQueue: "VERIFICATION BACKLOG",
    districtModernization: "District-Level Modernization Progress",
    today: "today",
    highConfidence: "HIGH CONFIDENCE",
    awaitingVerifier: "Awaiting Human Verifier",
    ingestBtn: "Ingest New Document",
    recordsProcessing: "Records Processing",
    complete: "Complete",
    dashboardTab: "Dashboard",
    exploreTab: "Explore",
    citizenTab: "Citizen Portal",
    uploadTab: "Upload",
    queueTab: "Queue",
    gisTab: "GIS Map",
    verWorkspaceTitle: "Verification Workspace & OCR Inspector",
    verWorkspaceSubtitle: "Inspect EasyOCR extracted text against original scanned land records with real-time bounding box sync.",
    ocrOverlaysBtn: "OCR Overlays",
    rawScanBtn: "Raw Scan",
    textLayerBtn: "Text Layer",
    forensicElaBadge: "Forensic ELA & Mutation Authenticity Analysis",
    approveSaveBtn: "Approve & Save Record",
    approvedLoggedBtn: "Approved & Logged to Audit Trail",
    resetEditsBtn: "Reset Edits",
    module3Title: "Module 3 · Human-in-the-Loop OCR Verification",
    assignedVerifier: "Assigned Verifier",
    docSelectorLabel: "Document:",
    extractedDataVerificationTitle: "Extracted Data Verification",
    imageElaCheckLabel: "Image ELA Tamper Check",
    mutationLedgerLabel: "Mutation Ledger Match",
    villageCollisionLabel: "Village Claim Collision",
    villageAndCodeLabel: "Village & Code",
    khasraNumberLabel: "Khasra / Survey Number",
    flaggedForReviewLabel: "Flagged For Review",
    ocrHighlightHint: "Clicking this field highlights the corresponding OCR bounding box on the original document.",
    verNotesLabel: "Verification Notes / Audit Remarks",
    verNotesPlaceholder: "Record justification for field correction or verification audit...",
    uploadSectionTitle: "Upload Land Record Document",
    uploadSectionSubtitle: "Digitize legacy land documents with high-precision OCR and schema mapping.",
    dragDropTitle: "Drag & drop scanned land record here",
    dragDropSub: "or click to browse from your device",
    supportedFormats: "Supported formats: PDF, TIFF, JPG, PNG (Max 50MB)",
    docCategoryLabel: "Document Category",
    districtScopeLabel: "District Scope",
    primaryLanguageLabel: "Primary Language / OCR",
    startAiPipelineBtn: "Start AI Digitization",
    executingAiPipelineBtn: "Executing AI Pipeline...",
    pipelineLiveStatusTitle: "Pipeline Live Status",
    overallProgressLabel: "Overall Progress",
    stepStorage: "Storage Ingestion",
    stepOcr: "Multilingual OCR",
    stepStructuring: "LLM Structuring",
    stepValidation: "Validation",
  },
  bn: {
    headerGovIndia: "🇮🇳 ভারত সরকার | Govt. of India",
    headerDept: "মহারাষ্ট্র সরকার - রাজস্ব ও বন বিভাগ",
    headerTitle: "ভূনেত্র - রাজ্য ভূমি রেকর্ড আধুনিকীকরণ ব্যবস্থা",
    roleTag: "ভূমিকা:",
    roleOfficer: "রাজস্ব আধিকারিক",
    roleVerifier: "মাঠ যাচাইকারী",
    roleAdmin: "প্রশাসক",
    roleCivilian: "নাগরিক",
    officerLoginBtn: "অফিসার লগইন",
    citizenBadge: "নাগরিক ভূমি রেকর্ড পোর্টাল",
    citizenPortalTitle: "পাবলিক ল্যান্ড রেকর্ড সার্ভিস",
    citizenPortalSubtitle: "আপনার কাঙ্ক্ষিত জমির নথি নির্বাচন করুন, ডাটাবেস অনুসন্ধান করুন অথবা এআই দিয়ে যাচাই করুন।",
    step1DocType: "ধাপ ১: নথির প্রকার নির্বাচন করুন",
    step2GeoSearch: "ধাপ ২: ভৌগোলিক অবস্থান এবং অনুসন্ধানের বিবরণ",
    selectedDocBadge: "নির্বাচিত নথি:",
    selectDistrict: "জেলা নির্বাচন করুন",
    selectTaluka: "তালুক নির্বাচন করুন",
    selectVillage: "গ্রাম নির্বাচন করুন",
    searchRecordsBtn: "রেকর্ড অনুসন্ধান করুন",
    searchingBtn: "অনুসন্ধান চলছে...",
    searchPlaceholder: "সার্ভে / খতিয়ান নম্বর লিখুন...",
    ownerNamePlaceholder: "মালিকের নাম (ঐচ্ছিক)",
    searchTab: "অনুসন্ধান",
    verifyCopyTab: "এআই যাচাইকরণ",
    mutationStatusTab: "মিউটেশন স্থিতি",
    docType712Title: "ফর্ম ৭/১২ জমির খতিয়ান",
    docType712Desc: "মালিকানা অধিকার এবং ফসলের বিবরণ",
    docType8ATitle: "ফর্ম ৮-এ খাতা রেকর্ড",
    docType8ADesc: "সমস্ত জমির একত্রিত খতিয়ান ও রাজস্ব নির্ধারণ",
    docTypePropertyCardTitle: "সম্পত্তি কার্ড (সিটি সার্ভে)",
    docTypePropertyCardDesc: "শহুরে সম্পত্তির রেকর্ড",
    docTypeFerfarTitle: "মিউটেশন রেজিস্টার",
    docTypeFerfarDesc: "মালিকানা পরিবর্তনের ঐতিহাসিক রেকর্ড",
    docTypeSaleDeedTitle: "বিক্রয় দলিল ও দায়মুক্তি",
    docTypeSaleDeedDesc: "রেজিস্টার্ড দলিল ও ব্যাংক ঋণ তথ্য",
    gatNoLabel: "গাট নং",
    khataNoLabel: "খতিয়ান নং",
    downloadCertifiedPdfBtn: "📜 প্রশংসাপত্র ডাউনলোড করুন (22 Languages)",
    verifiedStateRecordBadge: "✔ যাচাইকৃত রাজ্য ভূমি রেকর্ড",
    digitallySignedGuarantee: "ডিজিটাল স্বাক্ষরিত ৭/১২ — রাজস্ব বিভাগ",
    ownerNameLabel: "মালিকের নাম",
    landAreaLabel: "মোট এলাকা",
    ownershipTypeLabel: "মালিকানার ধরন",
    liensLabel: "দায় ও ঋণ",
    uploadDocTab: "📄 নথি আপলোড",
    welcome: "স্বাগতম",
    subtitle: "এআই ভিত্তিক ভূমি রেকর্ড ডিজিটাইজেশন পোর্টাল",
    totalDigitized: "মোট ডিজিটাইজড রেকর্ড",
    avgConfidence: "গড় নির্ভুলতা",
    autoApproved: "স্বয়ংক্রিয় অনুমোদিত",
    pendingQueue: "যাচাইকরণ বাকি",
    districtModernization: "জেলা অগ্রগতি",
    today: "আজ",
    highConfidence: "উচ্চ নির্ভুলতা",
    awaitingVerifier: "অফিসার অনুমোদনের অপেক্ষায়",
    ingestBtn: "নতুন নথি আপলোড",
    recordsProcessing: "প্রক্রিয়াধীন",
    complete: "সম্পূর্ণ",
    dashboardTab: "ড্যাশবোর্ড",
    exploreTab: "এক্সপ্লোর",
    citizenTab: "নাগরিক পোর্টাল",
    uploadTab: "আপলোড",
    queueTab: "যাচাইকরণ",
    gisTab: "ম্যাপ / GIS",
    verWorkspaceTitle: "যাচাইকরণ ওয়ার্কস্পেস",
    verWorkspaceSubtitle: "মূল স্ক্যানের সাথে নিষ্কাশিত ডেটা মিলিয়ে দেখুন।",
    ocrOverlaysBtn: "ওসিআর বক্স",
    rawScanBtn: "মূল স্ক্যান",
    textLayerBtn: "টেক্সট লেয়ার",
    forensicElaBadge: "ফরেনসিক ইএলএ বিশ্লেষণ",
    approveSaveBtn: "অনুমোদন ও সংরক্ষণ",
    approvedLoggedBtn: "অনুমোদিত ও রেকর্ডকৃত",
    resetEditsBtn: "রিসেট করুন",
  },
  gu: {
    headerGovIndia: "🇮🇳 ભારત સરકાર | Govt. of India",
    headerDept: "મહારાષ્ટ્ર સરકાર - મહેસૂલ અને વન વિભાગ",
    headerTitle: "ભૂનેત્ર - રાજ્ય જમીન રેકોર્ડ આધુનિકીકરણ પ્રણાલી",
    roleTag: "હોદ્દો:",
    roleOfficer: "મામલતદાર / અધિકારી",
    roleVerifier: "તલાટી / ચકાસણીકર્તા",
    roleAdmin: "વહીવટકર્તા",
    roleCivilian: "નાગરિક",
    officerLoginBtn: "અધિકારી લૉગિન",
    citizenBadge: "નાગરિક જમીન રેકોર્ડ પોર્ટલ",
    citizenPortalTitle: "જાહેર જમીન રેકોર્ડ સેવા",
    citizenPortalSubtitle: "જમીન દસ્તાવેજનો પ્રકાર પસંદ કરો, રેકોર્ડ શોધો અથવા એઆઈ દ્વારા ચકાસણી કરો.",
    step1DocType: "પગલું ૧: દસ્તાવેજનો પ્રકાર પસંદ કરો",
    step2GeoSearch: "પગલું ૨: ભૌગોલિક સ્થાન અને શોધ વિગતો",
    selectedDocBadge: "પસંદ કરેલ દસ્તાવેજ:",
    selectDistrict: "જિલ્લો પસંદ કરો",
    selectTaluka: "તાલુકો પસંદ કરો",
    selectVillage: "ગામ પસંદ કરો",
    searchRecordsBtn: "રેકોર્ડ શોધો",
    searchingBtn: "શોધી રહ્યું છે...",
    searchPlaceholder: "સર્વે / ખાતા નંબર દાખલ કરો...",
    ownerNamePlaceholder: "નાગરિક / ખાતેદારનું નામ (વૈકલ્પિક)",
    searchTab: "શોધ",
    verifyCopyTab: "AI ચકાસણી",
    mutationStatusTab: "ફેરફાર સ્થિતિ",
    docType712Title: "ગામ નમૂનો ૭/૧૨ ઉતારો",
    docType712Desc: "સર્વે નંબર, ખાતેદાર હક્ક અને પાક વિગતો",
    docType8ATitle: "ગામ નમૂનો ૮-અ ખાતા નોંધ",
    docType8ADesc: "ખાતેદારની તમામ જમીનનું એકત્રિત ક્ષેત્રફળ",
    docTypePropertyCardTitle: "પ્રોપર્ટી કાર્ડ (સિટી સર્વે)",
    docTypePropertyCardDesc: "શહેરી મિલકત પત્રિકા રેકોર્ડ",
    docTypeFerfarTitle: "ફેરફાર નોંધ (હક્ક પત્રક)",
    docTypeFerfarDesc: "વારસાઈ, વેચાણ દસ્તાવેજ ફેરફાર ઇતિહાસ",
    docTypeSaleDeedTitle: "દસ્તાવેજ નોંધણી અને બોજો",
    docTypeSaleDeedDesc: "નોંધાયેલ દસ્તાવેજ અને બેંક ધિરાણ વિગતો",
    gatNoLabel: "ગટ નં.",
    khataNoLabel: "ખાતા નં.",
    downloadCertifiedPdfBtn: "📜 પ્રમાણપત્ર ડાઉનલોડ કરો (22 Languages)",
    verifiedStateRecordBadge: "✔ પ્રમાણિત રાજ્ય જમીન રેકોર્ડ",
    digitallySignedGuarantee: "ડિજિટલ સહી થયેલ ઉતારો — મહેસૂલ વિભાગ",
    ownerNameLabel: "ખાતેદારનું નામ",
    landAreaLabel: "કુલ ક્ષેત્રફળ",
    ownershipTypeLabel: "ધારણ પ્રકાર",
    liensLabel: "બોજો અને જવાબદારી",
    uploadDocTab: "📄 દસ્તાવેજ અપલોડ",
    welcome: "સુવાગતમ",
    subtitle: "એઆઈ આધારિત જમીન રેકોર્ડ ડિજિટાઇઝેશન પોર્ટલ",
    totalDigitized: "કુલ ડિજિટાઇઝ્ડ રેકોર્ડ્સ",
    avgConfidence: "સરેરાશ ચોકસાઈ",
    autoApproved: "સ્વચાલિત મંજૂર",
    pendingQueue: "ચકાસણી બાકી",
    districtModernization: "જિલ્લા પ્રગતિ",
    today: "આજે",
    highConfidence: "ઉચ્ચ ચોકસાઈ",
    awaitingVerifier: "અધિકારીની રાહ",
    ingestBtn: "નવો દસ્તાવેજ અપલોડ",
    recordsProcessing: "પ્રક્રિયા હેઠળ",
    complete: "પૂર્ણ",
    dashboardTab: "ડેશબોર્ડ",
    exploreTab: "એક્સપ્લોર",
    citizenTab: "નાગરિક પોર્ટલ",
    uploadTab: "અપલોડ",
    queueTab: "ચકાસણી",
    gisTab: "નકશો / GIS",
    verWorkspaceTitle: "ચકાસણી વર્કસ્પેસ",
    verWorkspaceSubtitle: "મૂળ સ્કેન સાથે કાઢેલ માહિતી સરખાવો.",
    ocrOverlaysBtn: "ઓસીઆર બોક્સ",
    rawScanBtn: "મૂળ સ્કેન",
    textLayerBtn: "ટેક્સ્ટ લેયર",
    forensicElaBadge: "ફોરેન્સિક ઈએલએ વિશ્લેષણ",
    approveSaveBtn: "મંજૂર અને સાચવો",
    approvedLoggedBtn: "મંજૂર અને નોંધાયેલ",
    resetEditsBtn: "ફેરફાર રદ કરો",
  },
  ta: {
    headerGovIndia: "🇮🇳 இந்திய அரசு | Govt. of India",
    headerDept: "மகாராஷ்டிர அரசு - வருவாய் மற்றும் வனத்துறை",
    headerTitle: "பூநேத்ரா - மாநில நில ஆவணங்கள் நவீனமயமாக்கல் அமைப்பு",
    roleTag: "பணி:",
    roleOfficer: "வருவாய் அலுவலர்",
    roleVerifier: "சரிபார்ப்பாளர்",
    roleAdmin: "நிர்வாகி",
    roleCivilian: "குடிமகன்",
    officerLoginBtn: "அலுவலர் உள்நுழைவு",
    citizenBadge: "குடிமக்கள் நில ஆவண போர்ட்டல்",
    citizenPortalTitle: "பொது நில ஆவண சேவை",
    citizenPortalSubtitle: "உங்கள் நில ஆவண வகையைத் தேர்ந்தெடுக்கவும், சரிபார்க்கப்பட்ட பதிவுகளைத் தேடவும் அல்லது AI மூலம் சரிபார்க்கவும்.",
    step1DocType: "படி 1: ஆவண வகையைத் தேர்ந்தெடுக்கவும்",
    step2GeoSearch: "படி 2: புவியியல் தேடல் அளவுருக்கள்",
    selectedDocBadge: "தேர்ந்தெடுக்கப்பட்ட ஆவணம்:",
    selectDistrict: "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்",
    selectTaluka: "வட்டத்தைத் தேர்ந்தெடுக்கவும்",
    selectVillage: "கிராமத்தைத் தேர்ந்தெடுக்கவும்",
    searchRecordsBtn: "ஆவணங்களைத் தேடுங்கள்",
    searchingBtn: "தேடுகிறது...",
    searchPlaceholder: "சர்வே / பட்டா எண் உள்ளிடவும்...",
    ownerNamePlaceholder: "உரிமையாளர் பெயர் (விருப்பத்திற்குரியது)",
    searchTab: "தேடல்",
    verifyCopyTab: "AI சரிபார்ப்பு",
    mutationStatusTab: "பட்டா மாறுதல் நிலை",
    docType712Title: "படிவம் 7/12 நில ஆவணம்",
    docType712Desc: "உரிமைகள், சர்வே எண் மற்றும் பயிர் சாகுபடி விவரங்கள்",
    docType8ATitle: "படிவம் 8-A பட்டா கணக்கு",
    docType8ADesc: "அனைத்து நிலங்களின் ஒருங்கிணைந்த பரப்பளவு மற்றும் வரி",
    docTypePropertyCardTitle: "சொத்து அட்டை (நகர சர்வே)",
    docTypePropertyCardDesc: "நகர்ப்புற சொத்து உரிமை பதிவு",
    docTypeFerfarTitle: "பட்டா மாறுதல் பதிவு (Ferfar)",
    docTypeFerfarDesc: "உரிமை பரிமாற்ற வரலாற்று பதிவு",
    docTypeSaleDeedTitle: "கிரய பத்திரம் மற்றும் வில்லங்கம்",
    docTypeSaleDeedDesc: "பதிவு செய்யப்பட்ட ஆவணம் மற்றும் வங்கி கடன் விவரம்",
    gatNoLabel: "சர்வே எண்",
    khataNoLabel: "பட்டா எண்",
    downloadCertifiedPdfBtn: "📜 சான்றிதழைப் பதிவிறக்குக (22 Languages)",
    verifiedStateRecordBadge: "✔ சரிபார்க்கப்பட்ட அரசு நில ஆவணம்",
    digitallySignedGuarantee: "டிஜிட்டல் கையொப்பமிடப்பட்ட ஆவணம் — வருவாய்த்துறை",
    ownerNameLabel: "உரிமையாளர் பெயர்",
    landAreaLabel: "மொத்த பரப்பளவு",
    ownershipTypeLabel: "உரிமை வகை",
    liensLabel: "வில்லங்க விவரங்கள்",
    uploadDocTab: "📄 ஆவண பதிவேற்றம்",
    welcome: "நல்வரவு",
    subtitle: "AI நில ஆவணங்கள் டிஜிட்டல் போர்ட்டல்",
    totalDigitized: "மொத்த டிஜிட்டல் ஆவணங்கள்",
    avgConfidence: "சராசரி துல்லியம்",
    autoApproved: "தானியங்கி அங்கீகரிக்கப்பட்டது",
    pendingQueue: "நிலுவையில் உள்ளவை",
    districtModernization: "மாவட்ட முன்னேற்றம்",
    today: "இன்று",
    highConfidence: "உயர் துல்லியம்",
    awaitingVerifier: "அலுவலர் ஒப்புதலுக்கு",
    ingestBtn: "புதிய ஆவணம் பதிவேற்று",
    recordsProcessing: "செயலாக்கத்தில் உள்ளது",
    complete: "நிறைவுற்றது",
    dashboardTab: "முகப்பு",
    exploreTab: "ஆராய்வு",
    citizenTab: "குடிமக்கள் போர்ட்டல்",
    uploadTab: "பதிவேற்றம்",
    queueTab: "சரிபார்ப்பு",
    gisTab: "வரைபடம் / GIS",
    verWorkspaceTitle: "சரிபார்ப்பு பணிமனை",
    verWorkspaceSubtitle: "அசல் ஆவணத்துடன் பிரித்தெடுக்கப்பட்ட தரவை ஒப்பிடுக.",
    ocrOverlaysBtn: "OCR பெட்டிகள்",
    rawScanBtn: "அசல் ஆவணம்",
    textLayerBtn: "உரை அடுக்கு",
    forensicElaBadge: "தடயவியல் ELA பகுப்பாய்வு",
    approveSaveBtn: "ஒப்புதல் & சேமி",
    approvedLoggedBtn: "ஒப்புதல் அளிக்கப்பட்டது",
    resetEditsBtn: "மீட்டமை",
  },
  te: {
    headerGovIndia: "🇮🇳 భారత ప్రభుత్వం | Govt. of India",
    headerDept: "మహారాష్ట్ర ప్రభుత్వం - రెవెన్యూ మరియు అటవీ శాఖ",
    headerTitle: "భూనేత్ర - రాష్ట్ర భూ రికార్డుల ఆధునీకరణ వ్యవస్థ",
    roleTag: "పదవి:",
    roleOfficer: "రెవెన్యూ అధికారి",
    roleVerifier: "క్షేత్ర పరిశీలకుడు",
    roleAdmin: "నిర్వాహకుడు",
    roleCivilian: "పౌరుడు",
    officerLoginBtn: "అధికారి లాగిన్",
    citizenBadge: "పౌర భూ రికార్డుల పోర్టల్",
    citizenPortalTitle: "ప్రజా భూ రికార్డుల సేవ",
    citizenPortalSubtitle: "మీ భూ పత్రం రకాన్ని ఎంచుకోండి, రికార్డులను శోధించండి లేదా AI ద్వారా ధృవీకరించండి.",
    step1DocType: "దశ 1: పత్రం రకాన్ని ఎంచుకోండి",
    step2GeoSearch: "దశ 2: భౌగోళిక శోధన వివరాలు",
    selectedDocBadge: "ఎంచుకున్న పత్రం:",
    selectDistrict: "జిల్లాను ఎంచుకోండి",
    selectTaluka: "తాలూకాను ఎంచుకోండి",
    selectVillage: "గ్రామాన్ని ఎంచుకోండి",
    searchRecordsBtn: "రికార్డులను శోధించండి",
    searchingBtn: "శోధిస్తోంది...",
    searchPlaceholder: "సర్వే / ఖాతా సంఖ్య నమోదు చేయండి...",
    ownerNamePlaceholder: "పౌరుడు / యజమాని పేరు (ఐచ్ఛికం)",
    searchTab: "శోధన",
    verifyCopyTab: "AI ధృవీకరణ",
    mutationStatusTab: "మ్యుటేషన్ స్థితి",
    docType712Title: "గ్రామ నమూనా 7/12 పత్రం",
    docType712Desc: "సర్వే నంబర్, యాజమాన్య హక్కులు మరియు పంట వివరాలు",
    docType8ATitle: "గ్రామ నమూనా 8-A ఖాతా పత్రం",
    docType8ADesc: "మొత్తం భూమి విస్తీర్ణం మరియు రెవెన్యూ అంచనా",
    docTypePropertyCardTitle: "ఆస్తి కార్డ్ (సిటీ సర్వే)",
    docTypePropertyCardDesc: "పట్టణ మున్సిపల్ ఆస్తి రికార్డు",
    docTypeFerfarTitle: "మ్యుటేషన్ రిజిస్టర్ (Ferfar)",
    docTypeFerfarDesc: "యాజమాన్య మార్పిడి చారిత్రక రికార్డు",
    docTypeSaleDeedTitle: "క్రయ విక్రయ పత్రం & తాకట్టు",
    docTypeSaleDeedDesc: "రిజిస్టర్డ్ పత్రాలు మరియు బ్యాంక్ రుణ వివరాలు",
    gatNoLabel: "సర్వే నం.",
    khataNoLabel: "ఖాతా నం.",
    downloadCertifiedPdfBtn: "📜 ధృవీకరించబడిన PDF డౌన్‌లోడ్ (22 Languages)",
    verifiedStateRecordBadge: "✔ ధృవీకరించబడిన రాష్ట్ర భూ రికార్డు",
    digitallySignedGuarantee: "డిజిటల్ సంతకం చేయబడిన పత్రం — రెవెన్యూ శాఖ",
    ownerNameLabel: "యజమాని పేరు",
    landAreaLabel: "మొత్తం విస్తీర్ణం",
    ownershipTypeLabel: "యాజమాన్య రకం",
    liensLabel: "రుణాలు మరియు తాకట్టు",
    uploadDocTab: "📄 పత్రం అప్‌లోడ్",
    welcome: "సుస్వాగతం",
    subtitle: "AI భూ రికార్డుల డిజిటలైజేషన్ పోర్టల్",
    totalDigitized: "మొత్తం డిజిటలైజ్ చేసిన రికార్డులు",
    avgConfidence: "సగటు ఖచ్చితత్వం",
    autoApproved: "ఆటో ఆమోదించబడింది",
    pendingQueue: "పెండింగ్ రికార్డులు",
    districtModernization: "జిల్లా పురోగతి",
    today: "ఈరోజు",
    highConfidence: "అధిక ఖచ్చితత్వం",
    awaitingVerifier: "అధికారి ఆమోదం కోసం",
    ingestBtn: "కొత్త పత్రం అప్‌లోడ్ చేయండి",
    recordsProcessing: "ప్రాసెసింగ్‌లో ఉంది",
    complete: "పూర్తయింది",
    dashboardTab: "డాష్‌బోర్డ్",
    exploreTab: "అన్వేషించండి",
    citizenTab: "పౌర పోర్టల్",
    uploadTab: "అప్‌లోడ్",
    queueTab: "పరిశీలన",
    gisTab: "మ్యాప్ / GIS",
    verWorkspaceTitle: "పరిశీలన వర్క్‌స్పేస్",
    verWorkspaceSubtitle: "అసలు పత్రంతో సంగ్రహించిన డేటాను పోల్చండి.",
    ocrOverlaysBtn: "OCR బాక్స్‌లు",
    rawScanBtn: "అసలు స్కాన్",
    textLayerBtn: "టెక్స్ట్ లేయర్",
    forensicElaBadge: "ఫోరెన్సిక్ ELA విశ్లేషణ",
    approveSaveBtn: "ఆమోదించి భద్రపరచండి",
    approvedLoggedBtn: "ఆమోదించబడింది",
    resetEditsBtn: "రీసెట్ చేయండి",
  },
  kn: {
    headerGovIndia: "🇮🇳 ಭಾರತ ಸರ್ಕಾರ | Govt. of India",
    headerDept: "ಮಹಾರಾಷ್ಟ್ರ ಸರ್ಕಾರ - ಕಂದಾಯ ಮತ್ತು ಅರಣ್ಯ ಇಲಾಖೆ",
    headerTitle: "ಭೂನೇತ್ರ - ರಾಜ್ಯ ಭೂ ದಾಖಲೆಗಳ ಆಧುನೀಕರಣ ವ್ಯವಸ್ಥೆ",
    roleTag: "ಹುದ್ದೆ:",
    roleOfficer: "ಕಂದಾಯ ಅಧಿಕಾರಿ",
    roleVerifier: "ಪರಿಶೀಲಕ",
    roleAdmin: "ನಿರ್ವಾಹಕ",
    roleCivilian: "ನಾಗರಿಕ",
    officerLoginBtn: "ಅಧಿಕಾರಿ ಲಾಗಿನ್",
    citizenBadge: "ನಾಗರಿಕ ಭೂ ದಾಖಲೆಗಳ ಪೋರ್ಟಲ್",
    citizenPortalTitle: "ಸಾರ್ವಜನಿಕ ಭೂ ದಾಖಲೆ ಸೇವೆ",
    citizenPortalSubtitle: "ನಿಮ್ಮ ಭೂ ದಾಖಲೆ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ, ದಾಖಲೆಗಳನ್ನು ಹುಡುಕಿ ಅಥವಾ AI ಮೂಲಕ ಪರಿಶೀಲಿಸಿ.",
    step1DocType: "ಹಂತ 1: ದಾಖಲೆ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    step2GeoSearch: "ಹಂತ 2: ಭೌಗೋಳಿಕ ಹುಡುಕಾಟ ವಿವರಗಳು",
    selectedDocBadge: "ಆಯ್ಕೆಮಾಡಿದ ದಾಖಲೆ:",
    selectDistrict: "ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    selectTaluka: "ತಾಲೂಕನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    selectVillage: "ಗ್ರಾಮವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    searchRecordsBtn: "ದಾಖಲೆಗಳನ್ನು ಹುಡುಕಿ",
    searchingBtn: "ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    searchPlaceholder: "ಸರ್ವೆ / ಖಾತೆ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ...",
    ownerNamePlaceholder: "ಖಾತೆದಾರರ / ನಾಗರಿಕರ ಹೆಸರು (ಐಚ್ಛಿಕ)",
    searchTab: "ಹುಡುಕಾಟ",
    verifyCopyTab: "AI ಪರಿಶೀಲನೆ",
    mutationStatusTab: "ಮ್ಯುಟೇಶನ್ ಸ್ಥಿತಿ",
    docType712Title: "ಗ್ರಾಮ ನಮೂನೆ 7/12 ದಾಖಲೆ",
    docType712Desc: "ಸರ್ವೆ ಸಂಖ್ಯೆ, ಮಾಲೀಕತ್ವದ ಹಕ್ಕುಗಳು ಮತ್ತು ಬೆಳೆ ವಿವರಗಳು",
    docType8ATitle: "ಗ್ರಾಮ ನಮೂನೆ 8-A ಖಾತೆ ಪತ್ರ",
    docType8ADesc: "ಒಟ್ಟು ಭೂ ವಿಸ್ತೀರ್ಣ ಮತ್ತು ಕಂದಾಯ ನಿರ್ಧಾರ",
    docTypePropertyCardTitle: "ಆಸ್ತಿ ಕಾರ್ಡ್ (ಸಿಟಿ ಸರ್ವೆ)",
    docTypePropertyCardDesc: "ನಗರ ಆಸ್ತಿ ಮಾಲೀಕತ್ವದ ದಾಖಲೆ",
    docTypeFerfarTitle: "ಮ್ಯುಟೇಶನ್ ರಿಜಿಸ್ಟರ್ (Ferfar)",
    docTypeFerfarDesc: "ಹಕ್ಕು ಬದಲಾವಣೆಯ ಐತಿಹಾಸಿಕ ದಾಖಲೆ",
    docTypeSaleDeedTitle: "ಕ್ರಯ ಪತ್ರ ಮತ್ತು ಹೊಣೆಗಾರಿಕೆ",
    docTypeSaleDeedDesc: "ನೋಂದಾಯಿತ ಪತ್ರ ಮತ್ತು ಬ್ಯಾಂಕ್ ಸಾಲ ವಿವರಗಳು",
    gatNoLabel: "ಸರ್ವೆ ನಂ.",
    khataNoLabel: "ಖಾತೆ ನಂ.",
    downloadCertifiedPdfBtn: "📜 ಪ್ರಮಾಣಪತ್ರ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ (22 Languages)",
    verifiedStateRecordBadge: "✔ ಪರಿಶೀಲಿಸಿದ ರಾಜ್ಯ ಭೂ ದಾಖಲೆ",
    digitallySignedGuarantee: "ಡಿಜಿಟಲ್ ಸಹಿ ಮಾಡಿದ ದಾಖಲೆ — ಕಂದಾಯ ಇಲಾಖೆ",
    ownerNameLabel: "ಮಾಲೀಕರ ಹೆಸರು",
    landAreaLabel: "ಒಟ್ಟು ವಿಸ್ತೀರ್ಣ",
    ownershipTypeLabel: "ಮಾಲೀಕತ್ವದ ಪ್ರಕಾರ",
    liensLabel: "ಸಾಲ ಮತ್ತು ಹೊಣೆಗಾರಿಕೆಗಳು",
    uploadDocTab: "📄 ದಾಖಲೆ ಅಪ್‌ಲೋಡ್",
    welcome: "ಸ್ವಾಗತ",
    subtitle: "AI ಭೂ ದಾಖಲೆಗಳ ಡಿಜಿಟಲೀಕರಣ ಪೋರ್ಟಲ್",
    totalDigitized: "ಒಟ್ಟು ಡಿಜಿಟಲೀಕೃತ ದಾಖಲೆಗಳು",
    avgConfidence: "ಸರಾಸರಿ ನಿಖರತೆ",
    autoApproved: "ಸ್ವಯಂ ಅನುಮೋದಿತ",
    pendingQueue: "ಬಾಕಿ ಉಳಿದಿರುವ ದಾಖಲೆಗಳು",
    districtModernization: "ಜಿಲ್ಲಾ ಪ್ರಗತಿ",
    today: "ಇಂದು",
    highConfidence: "ಹೆಚ್ಚಿನ ನಿಖರತೆ",
    awaitingVerifier: "ಅಧಿಕಾರಿ ಅನುಮೋದನೆಗಾಗಿ",
    ingestBtn: "ಹೊಸ ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    recordsProcessing: "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ",
    complete: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    dashboardTab: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    exploreTab: "ಅನ್ವೇಷಿಸಿ",
    citizenTab: "ನಾಗರಿಕ ಪೋರ್ಟಲ್",
    uploadTab: "ಅಪ್‌ಲೋಡ್",
    queueTab: "ಪರಿಶೀಲನೆ",
    gisTab: "ನಕ್ಷೆ / GIS",
    verWorkspaceTitle: "ಪರಿಶೀಲನಾ ಕಾರ್ಯಕ್ಷೇತ್ರ",
    verWorkspaceSubtitle: "ಮೂಲ ಸ್ಕ್ಯಾನ್‌ನೊಂದಿಗೆ ಹೊರತೆಗೆದ ಡೇಟಾವನ್ನು ಹೋಲಿಸಿ.",
    ocrOverlaysBtn: "OCR ಬಾಕ್ಸ್‌ಗಳು",
    rawScanBtn: "ಮೂಲ ಸ್ಕ್ಯಾನ್",
    textLayerBtn: "ಪಠ್ಯ ಪದರ",
    forensicElaBadge: "ಫೋರೆನ್ಸಿಕ್ ELA ವಿಶ್ಲೇಷಣೆ",
    approveSaveBtn: "ಅನುಮೋದಿಸಿ ಮತ್ತು ಉಳಿಸಿ",
    approvedLoggedBtn: "ಅನುಮೋದಿಸಲಾಗಿದೆ",
    resetEditsBtn: "ಮರುಹೊಂದಿಸಿ",
  },
  ml: {
    headerGovIndia: "🇮🇳 ഭാരത സർക്കാർ | Govt. of India",
    headerDept: "മഹാരാഷ്ട്ര സർക്കാർ - റവന്യൂ, വനം വകുപ്പ്",
    headerTitle: "ഭൂനേത്ര - സംസ്ഥാന ഭൂമി റിക്കോർഡുകൾ ആധുനികവൽക്കരണ സംവിധാനം",
    roleTag: "പദവി:",
    roleOfficer: "റവന്യൂ ഓഫീസർ",
    roleVerifier: "പരിശോധകൻ",
    roleAdmin: "അഡ്മിനിസ്ട്രേറ്റർ",
    roleCivilian: "പൗരൻ",
    officerLoginBtn: "ഓഫീസർ ലോഗിൻ",
    citizenBadge: "പൗര ഭൂമി റിക്കോർഡ് പോർട്ടൽ",
    citizenPortalTitle: "പബ്ലിക് ലാൻഡ് റെക്കോർഡ് സർവീസ്",
    citizenPortalSubtitle: "നിങ്ങൾക്ക് ആവശ്യമായ ഭൂമി രേഖ തിരഞ്ഞെടുക്കുക, റെക്കോർഡുകൾ തിരയുക അല്ലെങ്കിൽ AI വഴി പരിശോധിക്കുക.",
    step1DocType: "ഘട്ടം 1: രേഖയുടെ തരം തിരഞ്ഞെടുക്കുക",
    step2GeoSearch: "ഘട്ടം 2: ഭൂമിശാസ്ത്രപരമായ തിരയൽ വിശദാംശങ്ങൾ",
    selectedDocBadge: "തിരഞ്ഞെടുത്ത രേഖ:",
    selectDistrict: "ജില്ല തിരഞ്ഞെടുക്കുക",
    selectTaluka: "താലൂക്ക് തിരഞ്ഞെടുക്കുക",
    selectVillage: "വില്ലേജ് തിരഞ്ഞെടുക്കുക",
    searchRecordsBtn: "റെക്കോർഡുകൾ തിരയുക",
    searchingBtn: "തിരയുന്നു...",
    searchPlaceholder: "സർവേ / ഖാത നമ്പർ നൽകുക...",
    ownerNamePlaceholder: "ഉടമസ്ഥന്റെ പേര് (ഐച്ഛികം)",
    searchTab: "തിരയൽ",
    verifyCopyTab: "AI പരിശോധന",
    mutationStatusTab: "പോക്കുവരവ് സ്ഥിതി",
    docType712Title: "ഫോറം 7/12 അവകാശ രേഖ",
    docType712Desc: "സർവേ നമ്പർ, ഉടമസ്ഥാവകാശങ്ങൾ, വിള വിവരങ്ങൾ",
    docType8ATitle: "ഫോറം 8-A ഖാത രേഖ",
    docType8ADesc: "മൊത്തം ഭൂവിസ്തൃതിയും നികുതി നിർണ്ണയവും",
    docTypePropertyCardTitle: "പ്രോപ്പർട്ടി കാർഡ് (സിറ്റി സർവേ)",
    docTypePropertyCardDesc: "നഗര സ്വത്ത് ഉടമസ്ഥാവകാശ രേഖ",
    docTypeFerfarTitle: "പോക്കുവരവ് രജിസ്റ്റർ (Ferfar)",
    docTypeFerfarDesc: "ഉടമസ്ഥാവകാശ മാറ്റങ്ങളുടെ ചരിത്രം",
    docTypeSaleDeedTitle: "ആധാരവും ബാധ്യതയും",
    docTypeSaleDeedDesc: "രജിസ്റ്റർ ചെയ്ത ആധാരം, ബാങ്ക് വായ്പ വിവരങ്ങൾ",
    gatNoLabel: "സർവേ നം.",
    khataNoLabel: "ഖാത നം.",
    downloadCertifiedPdfBtn: "📜 സർട്ടിഫിക്കറ്റ് ഡൗൺലോഡ് ചെയ്യുക (22 Languages)",
    verifiedStateRecordBadge: "✔ സാക്ഷ്യപ്പെടുത്തിയ സംസ്ഥാന ഭൂമി രേഖ",
    digitallySignedGuarantee: "ഡിജിറ്റൽ ഒപ്പിട്ട രേഖ — റവന്യൂ വകുപ്പ്",
    ownerNameLabel: "ഉടമസ്ഥന്റെ പേര്",
    landAreaLabel: "ആകെ വിസ്തീർണം",
    ownershipTypeLabel: "ഉടമസ്ഥത തരം",
    liensLabel: "ബാധ്യതകൾ",
    uploadDocTab: "📄 രേഖ അപ്‌ലോഡ്",
    welcome: "സ്വാഗതം",
    subtitle: "AI അധിഷ്ഠിത ഭൂമി റിക്കോർഡ് ഡിജിറ്റലൈസേഷൻ പോർട്ടൽ",
    totalDigitized: "ആകെ ഡിജിറ്റൈസ് ചെയ്ത രേഖകൾ",
    avgConfidence: "ശരാശരി കൃത്യത",
    autoApproved: "യാന്ത്രികമായി അംഗീകരിച്ചത്",
    pendingQueue: "പരിശോധന ബാക്കിയുള്ളവ",
    districtModernization: "ജില്ലാ പുരോഗതി",
    today: "ഇന്ന്",
    highConfidence: "ഉയർന്ന കൃത്യത",
    awaitingVerifier: "ഓഫീസർ അംഗീകാരത്തിനായി",
    ingestBtn: "പുതിയ രേഖ അപ്‌ലോഡ് ചെയ്യുക",
    recordsProcessing: "പ്രക്രിയയിൽ",
    complete: "പൂർത്തിയായി",
    dashboardTab: "ഡാഷ്‌ബോർഡ്",
    exploreTab: "പര്യവേക്ഷണം",
    citizenTab: "പൗര പോർട്ടൽ",
    uploadTab: "അപ്‌ലോഡ്",
    queueTab: "പരിശോധന",
    gisTab: "മാപ്പ് / GIS",
    verWorkspaceTitle: "പരിശോധനാ വർക്ക്‌സ്‌പെയ്‌സ്",
    verWorkspaceSubtitle: "യഥാർത്ഥ സ്കാനുമായി വേർതിരിച്ചെടുത്ത ഡാറ്റ താരതമ്യം ചെയ്യുക.",
    ocrOverlaysBtn: "OCR ബോക്സുകൾ",
    rawScanBtn: "യഥാർത്ഥ സ്കാൻ",
    textLayerBtn: "ടെക്സ്റ്റ് ലെയർ",
    forensicElaBadge: "ഫോറൻസിക് ELA വിശകലനം",
    approveSaveBtn: "അംഗീകരിച്ച് സംരക്ഷിക്കുക",
    approvedLoggedBtn: "അംഗീകരിച്ചു",
    resetEditsBtn: "റീസെറ്റ് ചെയ്യുക",
  },
  pa: {
    headerGovIndia: "🇮🇳 ਭਾਰਤ ਸਰਕਾਰ | Govt. of India",
    headerDept: "ਮਹਾਰਾਸ਼ਟਰ ਸਰਕਾਰ - ਮਾਲੀਆ ਅਤੇ ਜੰਗਲਾਤ ਵਿਭਾਗ",
    headerTitle: "ਭੂਨੇਤਰ - ਰਾਜ ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ ਆਧੁਨਿਕੀਕਰਨ ਪ੍ਰਣਾਲੀ",
    roleTag: "ਭੂਮਿਕਾ:",
    roleOfficer: "ਮਾਲੀਆ ਅਧਿਕਾਰੀ (ਤਹਿਸੀਲਦਾਰ)",
    roleVerifier: "ਪਟਵਾਰੀ / ਤਸਦੀਕਕਾਰ",
    roleAdmin: "ਪ੍ਰਸ਼ਾਸਕ",
    roleCivilian: "ਨਾਗਰਿਕ",
    officerLoginBtn: "ਅਧਿਕਾਰੀ ਲੌਗਇਨ",
    citizenBadge: "ਨਾਗਰਿਕ ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ ਪੋਰਟਲ",
    citizenPortalTitle: "ਲੋਕ ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ ਸੇਵਾ",
    citizenPortalSubtitle: "ਆਪਣਾ ਲੋੜੀਂਦਾ ਜ਼ਮੀਨੀ ਦਸਤਾਵੇਜ਼ ਚੁਣੋ, ਪ੍ਰਮਾਣਿਤ ਰਿਕਾਰਡ ਖੋਜੋ ਜਾਂ AI ਰਾਹੀਂ ਤਸਦੀਕ ਕਰੋ।",
    step1DocType: "ਕਦਮ 1: ਦਸਤਾਵੇਜ਼ ਦੀ ਕਿਸਮ ਚੁਣੋ",
    step2GeoSearch: "ਕਦਮ 2: ਭੂਗੋਲਿਕ ਸਥਾਨ ਅਤੇ ਖੋਜ ਵੇਰਵੇ",
    selectedDocBadge: "ਚੁਣਿਆ ਦਸਤਾਵੇਜ਼:",
    selectDistrict: "ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ",
    selectTaluka: "ਤਹਿਸੀਲ ਚੁਣੋ",
    selectVillage: "ਪਿੰਡ ਚੁਣੋ",
    searchRecordsBtn: "ਰਿਕਾਰਡ ਖੋਜੋ",
    searchingBtn: "ਖੋਜ ਰਿਹਾ ਹੈ...",
    searchPlaceholder: "ਖਸਰਾ / ਖਾਤਾ ਨੰਬਰ ਦਰਜ ਕਰੋ...",
    ownerNamePlaceholder: "ਮਾਲਕ ਦਾ ਨਾਮ (ਵਿਕਲਪਿਕ)",
    searchTab: "ਖੋਜ",
    verifyCopyTab: "AI ਤਸਦੀਕ",
    mutationStatusTab: "ਇੰਤਕਾਲ ਸਥਿਤੀ",
    docType712Title: "ਫਾਰਮ 7/12 ਜਮ੍ਹਾਂਬੰਦੀ ਨਕਲ",
    docType712Desc: "ਮਲਕੀਅਤ ਹੱਕ, ਖਸਰਾ ਨੰਬਰ ਅਤੇ ਫ਼ਸਲ ਵੇਰਵਾ",
    docType8ATitle: "ਫਾਰਮ 8-A ਖਾਤਾ ਵੇਰਵਾ",
    docType8ADesc: "ਕੁੱਲ ਰਕਬਾ ਅਤੇ ਮਾਲੀਆ ਨਿਰਧਾਰਨ",
    docTypePropertyCardTitle: "ਪ੍ਰਾਪਰਟੀ ਕਾਰਡ (ਸਿਟੀ ਸਰਵੇ)",
    docTypePropertyCardDesc: "ਸ਼ਹਿਰੀ ਜਾਇਦਾਦ ਮਲਕੀਅਤ ਰਿਕਾਰਡ",
    docTypeFerfarTitle: "ਇੰਤਕਾਲ ਰਜਿਸਟਰ (Ferfar)",
    docTypeFerfarDesc: "ਵਿਰਾਸਤ, ਬੈਨਾਮਾ ਅਤੇ ਤਬਦੀਲੀ ਦਾ ਇਤਿਹਾਸ",
    docTypeSaleDeedTitle: "ਰਜਿਸਟਰੀ ਅਤੇ ਕਰਜ਼ਾ ਬੋਝ",
    docTypeSaleDeedDesc: "ਰਜਿਸਟਰਡ ਬੈਨਾਮਾ ਅਤੇ ਬੈਂਕ ਕਰਜ਼ਾ ਵੇਰਵਾ",
    gatNoLabel: "ਖਸਰਾ ਨੰ.",
    khataNoLabel: "ਖਾਤਾ ਨੰ.",
    downloadCertifiedPdfBtn: "📜 ਪ੍ਰਮਾਣ ਪੱਤਰ ਡਾਊਨਲੋਡ ਕਰੋ (22 Languages)",
    verifiedStateRecordBadge: "✔ ਪ੍ਰਮਾਣਿਤ ਰਾਜ ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ",
    digitallySignedGuarantee: "ਡਿਜੀਟਲ ਦਸਤਖਤੀ ਨਕਲ — ਮਾਲੀਆ ਵਿਭਾਗ",
    ownerNameLabel: "ਮਾਲਕ ਦਾ ਨਾਮ",
    landAreaLabel: "ਕੁੱਲ ਰਕਬਾ",
    ownershipTypeLabel: "ਕਿਸਮ ਮਲਕੀਅਤ",
    liensLabel: "ਕਰਜ਼ਾ ਤੇ ਬੋਝ",
    uploadDocTab: "📄 ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ",
    welcome: "ਜੀ ਆਇਆਂ ਨੂੰ",
    subtitle: "AI ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ ਡਿਜੀਟਾਈਜ਼ੇਸ਼ਨ ਪੋਰਟਲ",
    totalDigitized: "ਕੁੱਲ ਡਿਜੀਟਾਈਜ਼ਡ ਰਿਕਾਰਡ",
    avgConfidence: "ਔਸਤ ਸ਼ੁੱਧਤਾ",
    autoApproved: "ਸਵੈ-ਪ੍ਰਵਾਨਿਤ",
    pendingQueue: "ਜਾਂਚ ਲਈ ਬਾਕੀ",
    districtModernization: "ਜ਼ਿਲ੍ਹਾ ਤਰੱਕੀ",
    today: "ਅੱਜ",
    highConfidence: "ਉੱਚ ਸ਼ੁੱਧਤਾ",
    awaitingVerifier: "ਅਧਿਕਾਰੀ ਦੀ ਉਡੀਕ",
    ingestBtn: "ਨਵਾਂ ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ",
    recordsProcessing: "ਪ੍ਰੋਸੈਸਿੰਗ ਵਿੱਚ",
    complete: "ਮੁਕੰਮਲ",
    dashboardTab: "ਡੈਸ਼ਬੋਰਡ",
    exploreTab: "ਖੋਜੋ",
    citizenTab: "ਨਾਗਰਿਕ ਪੋਰਟਲ",
    uploadTab: "ਅੱਪਲੋਡ",
    queueTab: "ਤਸਦੀਕ",
    gisTab: "ਨਕਸ਼ਾ / GIS",
    verWorkspaceTitle: "ਤਸਦੀਕ ਵਰਕਸਪੇਸ",
    verWorkspaceSubtitle: "ਅਸਲ ਸਕੈਨ ਨਾਲ ਡਾਟਾ ਮਿਲਾਓ।",
    ocrOverlaysBtn: "OCR ਬਕਸੇ",
    rawScanBtn: "ਅਸਲ ਸਕੈਨ",
    textLayerBtn: "ਲਿਖਤ ਪੱਧਰ",
    forensicElaBadge: "ਫੋਰੈਂਸਿਕ ELA ਵਿਸ਼ਲੇਸ਼ਣ",
    approveSaveBtn: "ਮਨਜ਼ੂਰ ਕਰੋ ਅਤੇ ਸੰਭਾਲੋ",
    approvedLoggedBtn: "ਮਨਜ਼ੂਰਸ਼ੁਦਾ",
    resetEditsBtn: "ਰੀਸੈੱਟ ਕਰੋ",
  },
}

/**
 * Universal lookup helper across all 22 official languages with cascading fallback
 */
export function t(key, langCode = 'mr') {
  const selectedDict = UI_TRANSLATIONS[langCode]
  if (selectedDict && selectedDict[key]) {
    return selectedDict[key]
  }
  // Fallbacks: Hindi -> English -> Marathi -> key name
  if (UI_TRANSLATIONS['hi'] && UI_TRANSLATIONS['hi'][key]) {
    return UI_TRANSLATIONS['hi'][key]
  }
  if (UI_TRANSLATIONS['en'] && UI_TRANSLATIONS['en'][key]) {
    return UI_TRANSLATIONS['en'][key]
  }
  if (UI_TRANSLATIONS['mr'] && UI_TRANSLATIONS['mr'][key]) {
    return UI_TRANSLATIONS['mr'][key]
  }
  return key
}
